/// Uganda Districts List
/// Comprehensive list of districts in Uganda for filtering
class UgandaDistricts {
  // Major districts commonly used (popular locations)
  static const List<String> popularDistricts = [
    'Kampala',
    'Wakiso',
    'Mukono',
    'Jinja',
    'Mbale',
    'Mbarara',
    'Gulu',
    'Lira',
    'Arua',
    'Fort Portal',
  ];

  // Complete list of all Uganda districts (alphabetically sorted)
  static const List<String> allDistricts = [
    'Abim',
    'Adjumani',
    'Agago',
    'Alebtong',
    'Amolatar',
    'Amudat',
    'Amuria',
    'Amuru',
    'Apac',
    'Arua',
    'Budaka',
    'Bududa',
    'Bugiri',
    'Buhweju',
    'Buikwe',
    'Bukedea',
    'Bukomansimbi',
    'Bukwa',
    'Bulambuli',
    'Buliisa',
    'Bundibugyo',
    'Bunyangabu',
    'Bushenyi',
    'Busia',
    'Butaleja',
    'Butambala',
    'Butebo',
    'Buvuma',
    'Buyende',
    'Dokolo',
    'Gomba',
    'Gulu',
    'Hoima',
    'Ibanda',
    'Iganga',
    'Isingiro',
    'Jinja',
    'Kaabong',
    'Kabale',
    'Kabarole',
    'Kaberamaido',
    'Kagadi',
    'Kakumiro',
    'Kalangala',
    'Kaliro',
    'Kalungu',
    'Kampala',
    'Kamuli',
    'Kamwenge',
    'Kanungu',
    'Kapchorwa',
    'Kasese',
    'Katakwi',
    'Kayunga',
    'Kibaale',
    'Kiboga',
    'Kibuku',
    'Kiruhura',
    'Kiryandongo',
    'Kisoro',
    'Kitgum',
    'Koboko',
    'Kole',
    'Kotido',
    'Kumi',
    'Kwania',
    'Kween',
    'Kyankwanzi',
    'Kyegegwa',
    'Kyenjojo',
    'Kyotera',
    'Lamwo',
    'Lira',
    'Luuka',
    'Luwero',
    'Lwengo',
    'Lyantonde',
    'Manafwa',
    'Maracha',
    'Masaka',
    'Masindi',
    'Mayuge',
    'Mbale',
    'Mbarara',
    'Mitooma',
    'Mityana',
    'Moroto',
    'Moyo',
    'Mpigi',
    'Mubende',
    'Mukono',
    'Nakapiripirit',
    'Nakaseke',
    'Nakasongola',
    'Namayingo',
    'Namisindwa',
    'Namutumba',
    'Napak',
    'Nebbi',
    'Ngora',
    'Ntoroko',
    'Ntungamo',
    'Nwoya',
    'Obongi',
    'Omoro',
    'Otuke',
    'Oyam',
    'Pader',
    'Pakwach',
    'Pallisa',
    'Rakai',
    'Rubanda',
    'Rubirizi',
    'Rukiga',
    'Rukungiri',
    'Sembabule',
    'Serere',
    'Sheema',
    'Sironko',
    'Soroti',
    'Tororo',
    'Wakiso',
    'Yumbe',
    'Zombo',
  ];

  /// Get districts list for dropdown/selection
  static List<String> getDistricts({bool popularOnly = false}) {
    return popularOnly ? popularDistricts : allDistricts;
  }

  /// Check if a district exists
  static bool isValidDistrict(String district) {
    return allDistricts.contains(district);
  }
}
