// Uganda Location Data Model
// Provides hierarchical location data structure for Uganda
// District -> Subcounty -> Parish -> Village
// Data source: Official Uganda administrative divisions (Complete Dataset)

class UgandaLocationData {
  // Complete hierarchical location data structure
  static final Map<String, Map<String, Map<String, List<String>>>> _locationData = {
    'BUGIRI': {
      'BUDHAYA': {
        'BUDHAYA': ['BUDHAYA', 'BUKEREKERE', 'BUMWANGU', 'KIWANDANGABO', 'NABUKALU', 'NGULUMO'],
        'BUKATU': ['BUBANGO', 'BUDIBYA', 'BUKATU', 'BULYANSWA', 'KAWOLOGOMA', 'MAZIRIGA', 'NAMATU'],
        'MAYUGE RURAL': ['BULYAIYOBYO', 'MUSIRISISI', 'NSAVU', 'WALUMBE'],
      },
      'BULESA': {
        'BULUWE': ['BULUWE', 'BUTEGWA A', 'BUTEGWA B', 'KIDOWO', 'MALENDELE', 'NANGALAMA'],
        'IGGWE': ['BULEBI', 'BUWAGAMA', 'LUWERO', 'MAWERERE', 'NAKABALE A', 'NAMIGUWA'],
        'KITODHA': ['IDHUBU', 'KITODHA', 'LUVUNYA', 'NAKISAMO', 'NAWANSONGA'],
        'NAMASERE': ['BUKOVU', 'BUKUTA', 'BULESA', 'NAKABALE B', 'NAKIGUNJU', 'NKINDHA'],
      },
      'BULIDHA': {
        'BULIDHA A': ['BULIDHA NABINOGA', 'NAKYEGEREIKE', 'NANSAGA', 'NANYONJO'],
        'BULIDHA B': ['BUKUDULU', 'ITOOLO'],
        'ISAKABUSOLO': ['BUSINDA', 'ISAKABUSOLO', 'MATYAMA', 'NAMUNGODI'],
        'MAKOMA': ['BUSAKIRA', 'BUSANO', 'MAKOMA I', 'MASOLYA', 'NAKISENYI'],
        'NABIGINGO': ['KISENYI', 'MAYOLE', 'MUFUMI', 'NABIGINGO A', 'NABIGINGO B'],
        'WAKAWAKA': ['KIBUYE A', 'KIBUYE B', 'NAGURU', 'NAKAWA', 'WAKAWAKA'],
      },
      'BULUGUYI': {
        'BUFUNDA': ['BUDUNYI', 'BUFUNDA \'A\'', 'BUFUNDA \'B\'', 'GAWUNIRE'],
        'BUGAYI': ['BUGAYI', 'BULESI', 'BUTUNDULA'],
        'NSANGO': ['BUDEMBE', 'HASHEBA', 'KAYAGO', 'KISOKO', 'MADENGHO', 'MUSOMA', 'NSANGO'],
      },
      'BUSOWA TOWN COUNCIL': {
        'BUDUNDULI WARD': ['BUGONGO', 'BUTEEBE', 'MAKALU', 'NAMALENHA'],
        'BULUME WARD': ['BUBONGOYI', 'BULUME A', 'BULUME B', 'BUSANGIRIZI A', 'BUSANGIRIZI B'],
        'NABIKAKA WARD': ['BUSOWA SOUTH A', 'BUSOWA SOUTH B', 'BUSOWA SOUTH C', 'TAKIWEREZA'],
        'NAKAWA WARD': ['ABALLA', 'NAKAWA', 'NAWANYAGO'],
        'NAKIDUDULA WARD': ['BUSOWA CENTRAL A', 'BUSOWA CENTRAL B', 'BUSOWA CENTRAL C', 'BUSOWA NORTH'],
        'NAWANDHUKI WARD': ['KIKWAYA', 'KINABIRYE', 'NAWANDHUKI'],
      },
      'BUWUNGA': {
        'BUBUGO': ['BUBUGO/BULIWAIGULU', 'BUBUNIRA', 'BUKEREWE', 'KIRONGO', 'NAMBOFA'],
        'BUPALA': ['BUPALA', 'KITOGO', 'KYALUYA A', 'KYALUYA B', 'WALUGOMA', 'WANZERERE'],
        'BUSOGA': ['BUSOGA', 'BUWUGE', 'NABIRARA', 'NAKAMINI', 'NAKISENYI'],
        'BUWUNGA': ['BUDIIDI', 'MUGERA', 'NAMALENHA', 'NAMATANGA', 'WANDEGEIRE'],
        'KAVULE': ['BUKEREKERE', 'KASAALA', 'KATOOKO', 'KAVULE CENTRAL'],
        'LUWOOKO': ['BUKALAIKOTI', 'KITEIGALWA', 'LUWOOKO A', 'LUWOOKO B', 'LUWOOKO CENTRAL'],
        'MAGOOLA': ['IMULI', 'KAYANDHA KATO', 'MAGOOLA', 'MAKOMA', 'NAKATWE'],
        'MAWANGA': ['BUDHEBERO', 'BUSAMBIRA', 'MAWANGA', 'NAKAWA'],
        'NAMBALE': ['BUGOMBO', 'BUTUMBA', 'KATALA', 'KAYAIGO', 'NAMBALE'],
      },
      'BUWUNI TOWN COUNCIL': {
        'BUWUNI RURAL WARD': ['BUGOSERE A', 'BUGOSERE B', 'BULENDE', 'BUWUNI'],
        'BUWUNI WARD': ['BUYEBE A', 'BUYEBE B', 'BUYEBE C', 'BUYEBE D'],
        'KASEBERE WARD': ['BUBUZI A', 'BUBUZI B', 'KASEBERE A', 'KASEBERE B'],
        'MAKHOMA NORTH WARD': ['KIBIMBA', 'MAKHOMA A', 'MAKHOMA NORTH', 'MAKHOMA WEST'],
        'MAKHOMA SOUTH WARD': ['MAKHOMA B', 'MAKHOMA C', 'MAKHOMA D'],
        'NAINALA WARD': ['NAINALA A', 'NAINALA B', 'NAINALA C', 'NAMAGONJO'],
        'NAMASERE B WARD': ['BUTUKA', 'NAWAMBIDHI A', 'NAWAMBIDHI B'],
        'NANKONKOLO WARD': ['MUCHOMO', 'NANKONKOLO A', 'NANKONKOLO B'],
      },
      'EASTERN DIVISION': {
        'NALUWERERE WARD': ['BUTAMBULA CENTRAL', 'BUTAMBULA EAST', 'BUTAMBULA WEST', 'KIWALAZI', 'KIYINIKIBI EAST', 'KIYINIKIBI WEST'],
        'NKUSI WARD': ['KATAWO', 'MUKUBA', 'NKUSI A', 'NKUSI B'],
      },
      'IWEMBA': {
        'BUGESO': ['BUKAKAIRE', 'KAZIMBAKUNGIRA', 'NABYUNU'],
        'BUYALA': ['BUDOME', 'BUKASOLO', 'BUYALA', 'KIGULU', 'KIMIRA'],
        'IWEMBA': ['BUKANDA', 'BUKIRI', 'BULYAMBOLI', 'BUSIMBA'],
        'NABIRERE': ['BUSOLO', 'KASOKWE', 'NABIRERE', 'WALUSAKA'],
        'NAMBO': ['NAMBO \'\'B\'\'', 'NAWANGALI', 'WALIKO'],
      },
      'KAPYANGA': {
        'BUGIRI A': ['BUGODHANDHALA', 'BUTAKANIRA', 'BUYUBU', 'KAPYANGA', 'NAITOSI'],
        'BUGUBO': ['BUBETA', 'BUGUBO', 'BUSANZI \'A\'', 'KAKANDWA', 'MUYEMU', 'NABYUNYU'],
        'BUGUNGA': ['BUDIBYA', 'BUGUNGA', 'BUJAKA', 'BUSOLO', 'BUSWIRIRI', 'KAWEMPE'],
        'KISEITAKA': ['KAATO', 'KIRONGERO \'A\'', 'KIRONGERO \'B\'', 'KISEITAKA', 'NAMINYAGWE', 'WANENGA'],
        'NAKAVULE': ['IZIRA', 'KAMANGO', 'KIDHEBERO', 'KIKABALA', 'NAKAVULE'],
        'NAMUKONGE': ['BUGODO \'A\'', 'BUGODO \'B\'', 'BUKAYE \'A\'', 'BUKAYE \'B\'', 'BUWOFU', 'IGOGO', 'KAYANGO \'A\'', 'KAYANGO \'B\'', 'KAYANGO \'C\''],
        'NDIFAKULYA': ['BUKAYE', 'LWABA', 'MUGONA NORTH', 'MUGONA SOUTH', 'NDIFAKULYA'],
      },
      'MAYUGE TOWN COUNCIL': {
        'BUDDE WARD': ['BUDDE', 'BUKAGOLO', 'BUVUTWA', 'GALASE', 'NABWALA'],
        'BUWOLYA WARD': ['BUTIBWA', 'MAKOOVA', 'MAKOOVA CENTRAL'],
        'KIMASA WARD': ['BUVUTWA CENTRAL', 'KIMASA', 'KIMBUGUTI', 'LUWA'],
        'KOLOLO WARD': ['KAMWOKYA', 'KOLOLO', 'KOLOLO WEST', 'NANTAKYA B'],
        'MAYUGE WARD': ['MAYUGE CENTRAL A', 'MAYUGE CENTRAL B', 'MAYUGE EAST', 'NANTAKYA A', 'NTEBBE'],
        'NILE WARD': ['EAST NILE', 'NILE A', 'NILE MARKET', 'WEST NILE'],
      },
      'MUTELELE TOWN COUNCIL': {
        'BUSINI WARD': ['BUSINI A', 'BUSINI B', 'CENTRAL'],
        'LYAVALA WARD': ['KABUGUTE', 'KYAIKU EAST', 'KYAIKU WEST'],
        'MUTANDA WARD': ['BUKABUDDO', 'KIGUSA A', 'NSIMBIRANO A', 'NSIMBIRANO B', 'NSIMBIRANO C'],
        'MUTERERE EAST WARD': ['KIGUSA B', 'KIREKA', 'KYOTAITE', 'MUTERERE WEST', 'NGOBI'],
        'NAKASERO WARD': ['BUWAYE', 'FATISHO', 'MUTERERE CENTRAL', 'MUTERERE EAST', 'NKAYE'],
      },
      'MUTERERE': {
        'BULULU': ['BULULU', 'BULYAIYOBYO', 'BUWENDA', 'LUBANYI', 'NABUYANDA', 'NONGO'],
        'KAYOGERA': ['BUKIIRI', 'BUWEMBULA', 'KAYOGERA', 'NAIGOMA', 'NAKABALE', 'NALUYA', 'NAWANKINGA'],
        'KITUMBA': ['IRIMBI', 'IVUMANGABO EAST', 'IVUMANGABO WEST', 'KIMBALE', 'KITUMBA', 'NAMUNTENGA', 'NGUNGA'],
      },
      'MUWAYO TOWN COUNCIL': {
        'BUDUMA WARD': ['BUDUMA A', 'BUDUMA B', 'BUKHOHE', 'BUTEMA', 'NAKAWA'],
        'BULUGUYI WARD': ['BUBWOKI', 'BULUGUYI', 'BUYINDI', 'KITOVU', 'LUGANO'],
        'MUWAYO WARD': ['HALF LONDON', 'MUDAWO', 'MUWAYO EAST', 'MUWAYO WEST', 'NAMUWOMBI'],
      },
      'NABUKALU': {
        'BUKUBANSIRI': ['BUKUBANSIRI', 'BUSOWOBI', 'NAKITAKA', 'NAWAMBIRI', 'WABUGESA'],
        'BUTYABULE': ['BUTYABULE', 'BUZIKA', 'KYABAKAIRE', 'NABUGANGA', 'NAKABALE', 'NAKAKONO', 'NAWANSEGA'],
        'ISEGERO': ['BUKWAKU', 'BUWOLOGOMA', 'ISEGERO', 'ITANDA', 'NABUKIMA', 'NAKAVULE'],
        'LWANIKA': ['KIWONGOLO', 'LWANIKA CENTRAL', 'LWANIKA NORTH', 'LWANIKA SOUTH'],
        'NKAIZA': ['BUKAZITO', 'BULALO', 'BULANGA', 'KAKOGE'],
        'WANGOBO': ['BUKAKAIRE', 'BUSAALA', 'BUSWIRIRI', 'BUZIBA', 'ITENTE', 'NSOKWE'],
      },
      'NABUKALU TOWN COUNCIL': {
        'BUBALYA WARD': ['BUBALYA', 'KIDHUDUULA', 'KIGENYI', 'MAGALAMA', 'NAIGAGA', 'WANYANGE'],
        'BUKYANSIKO WARD': ['BUGUMYA', 'BUKYANSIKO', 'BULENDE', 'BUTUMBA', 'KASOOBA', 'KATETEMPE'],
        'KALULU WARD': ['BUKANDA', 'KITUMBA', 'MASANDA', 'NAMAKOKO'],
        'KASITA WARD': ['BUDHEBERO', 'KAKINDU', 'MAGOLO', 'NAMADHI'],
        'LUYA WARD': ['BUDWADU', 'BUYAYA', 'KABASALA', 'NAWANZU'],
        'NABUKALU WARD': ['BUTONGOLE', 'NABUKALU', 'NABWEYA', 'NAMUNDOLERA'],
        'NAKIVAMBA WARD': ['BUDANDO', 'BUKAYE', 'BUKYEMANTA', 'BUTUUKA', 'NAWAMPENDO'],
      },
      'NAMAYEMBA TOWN COUNCIL': {
        'BUKONDE WARD': ['BUKONDE A', 'BUKONDE B'],
        'GULIMWOYO WARD': ['EKWARO', 'KAJUMBURA', 'MAJENGO', 'NAMAYEMBA CENTRAL A', 'NAMAYEMBA CENTRAL B', 'SCHEME'],
        'ISAGAZA WARD': ['BUBUGU', 'ISAGAZA A', 'ISAGAZA B', 'ISAGAZA NORTH'],
        'KAFUFU WARD': ['IBUKKA', 'KAFUFU', 'NAMAYEMBA WEST A', 'NAMAYEMBA WEST B', 'ODEWO'],
        'KASULE WARD': ['AGAITANO', 'KISUMU', 'NAMAYEMBA EAST A', 'NAMAYEMBA EAST B'],
        'NAMABUGO WARD': ['BUDEEBI', 'BUGOYOZI A', 'BUGOYOZI B', 'GO DOWN', 'NAMBOGO', 'SAMYA'],
      },
      'NANKOMA': {
        'ISEGERO': ['BWALULA \'A\'', 'BWALULA \'B\'', 'ISEGERO', 'MATIKI', 'WANSIMBA A', 'WANSIMBA B'],
        'MATOVU': ['KIGOBERO', 'MATOVU \'A\'', 'MATOVU \'B\'', 'MATOVU C', 'NAMAKOLI', 'NAMPERE', 'NAWAMBWA', 'NAWAMBWA B'],
        'NAMAKOKO': ['BUKAGOLO', 'BULYANGADA', 'BUMUNKU', 'BUSIMBI A', 'BUSIMBI B', 'BUTEGWA A', 'BUTEGWA B', 'LWANGOSA', 'NAMAKOKO'],
        'NSONO': ['KASONGOIRE A', 'KASONGOIRE B', 'KYAZUKA', 'NABULUNGI', 'NAMUGANZA', 'NAWANSENYU', 'NSONO', 'SANIKA'],
      },
      'NANKOMA TOWN COUNCIL': {
        'ITAKAIBOLU WARD': ['ITAKAIBOLU \'A\'', 'ITAKAIBOLU \'B\'', 'LWAMUNYU', 'NAWAMPANDA'],
        'MASITA WARD': ['BUDHEBERA', 'MASITA', 'NAKASISI A', 'NAKASISI B'],
        'NAKASITA WARD': ['KYEMEIRE', 'NAKASITA', 'NALWESAMBULA'],
        'NAMUNTENGA WARD': ['KASOBA A', 'KASOBA B', 'NAMUTENGA A', 'NAMUTENGA B'],
        'NANKOMA CENTRAL WARD': ['NANKOMA B', 'NANKOMA C', 'NANKOMA WEST'],
        'NANKOMA EAST WARD': ['KISAWO', 'NANKOMA A', 'NANKOMA EAST'],
        'NAWANGO WARD': ['NAMUNDORELA', 'NANKOMA D', 'NAWANGO A', 'NAWANGO B'],
      },
      'WESTERN DIVISION': {
        'BWOLE WARD': ['BUSANZI \'B\'', 'BWOLE', 'KAMWOKYA', 'MUSONGOLA'],
        'NDIFAKULYA A WARD': ['KIMOMBASA', 'KIREKA', 'MUYENGA', 'NDEEBA', 'NDIFAKULYA'],
      },
    },
    'BUGWERI': {
      'BUSEMBATIA TOWN COUNCIL': {
        'BUSEMBATIA CENTRAL WARD': ['BUSEMBATIA ZONE IV', 'BUTANDWE (ZONE VI)'],
        'BUSEMBATIA MARKET WARD': ['BUSEMBATIA ZONE II', 'BUSEMBATIA ZONE III'],
        'BUYIRIMA WARD': ['BUYIRIMA A', 'BUYIRIMA B'],
        'KAKOGE WARD': ['KAKOGE A', 'KAKOGE B'],
        'MAJENGO WARD': ['BUBONYE', 'MAJENGO'],
      },
      'BUSESA TOWN COUNCIL': {
        'BUTENDE WARD': ['BUKOTEKA', 'BUTENDE', 'LUSAGHA'],
        'IBAAKO WARD': ['BUSESA', 'IBAAKO', 'KAGAMBA', 'NAMIYANGU'],
      },
      'BUYANGA': {
        'BULUNGULI': ['BULUNGULI', 'KIWANYI A', 'KIWANYI B'],
        'BUMOOZI': ['BUBONYI', 'BUMOOZI', 'BUPALA', 'BUWANGA', 'NKOMBE', 'NSOZIBIRI'],
        'BUWOOYA': ['BUBBALA', 'BUDHUBYE', 'BUWOOYA A', 'BUWOOYA B', 'BUYANGA A', 'BUYANGA B', 'BUYANGA C', 'BUYIRIMA', 'NASILARO'],
        'BWIGULA': ['BUBINGA', 'BUKASOZI', 'BUTABA', 'BWIGULA', 'NAKAWOIZA'],
        'KALALU': ['KALALU A', 'KALALU B'],
        'LUBIRA': ['BUTYABULE', 'LUBIRA'],
      },
      'IBULANKU': {
        'BUNIANTOLE': ['BUNIANTOLE', 'BUTENKAIRE', 'KABUGWERI'],
        'IBULANKU': ['BUSOOLERA', 'IBULANKU', 'MULANGA'],
        'NAMIGANDA': ['BUKENKE', 'NAMIGANDA'],
        'NAWANSEGA': ['BUGHODANDALA', 'BUMPINGU', 'BUSOOLA', 'BUWANGA', 'NAKISENE', 'NAWANSEGA'],
        'NSAALE': ['BUWAABE', 'BUYEBE', 'NAKASUBI', 'NAKIBEMBE', 'NSAALE', 'WANTE'],
      },
      'IDUDI TOWN COUNCIL': {
        'IDUDI A WARD': ['IDUDI BUKAMBO', 'IDUDI NORTH', 'IDUDI OGAYA', 'IDUDI WEST'],
        'IDUDI B WARD': ['BUZAMA EAST', 'MUGOYA WEST'],
        'IDUDI C WARD': ['IDUDI MUTEGA NORTH', 'KYOZIRA SOUTH'],
        'IDUDI D WARD': ['BUGAMBUZE CENTRAL', 'DHAMUSAMULA EAST', 'GONGO WEST'],
        'KIKUNYU WARD': ['BUKABEGA', 'KIYOYI', 'NAKAWA', 'NAKITIBA'],
        'MIFUMI WARD': ['MIFUMI CENTRAL', 'MIFUMI SOUTH', 'NAWAMPITI'],
      },
      'IGOMBE': {
        'BUBENGE': ['BUBENGE A', 'BUBENGE B', 'MATOVU'],
        'IGOMBE': ['BULYANSIME', 'BUTALANGO', 'IGOMBE', 'MBULAMUTI', 'NAMAKUNYU'],
        'KIKUNYU': ['BUBINGA', 'BUBONGHE', 'BUSINDA', 'KIKUNYU', 'MPIITA'],
        'WALANGA': ['NAWAMPENDO', 'WALANGA'],
      },
      'MAKUUTU': {
        'KASOZI': ['BUKONDE', 'BUKOSE', 'BUKOWE', 'BUNAKATE', 'BUSIIMO A', 'BUSIIMO B', 'KASOZI A', 'KASOZI B', 'NAMAVUNDU', 'NONDWE', 'WAIBALE'],
        'KIGULAMO': ['BUBETO', 'KIGULAMO', 'NAITANDU A', 'NAITANDU B'],
        'MAKANDWA': ['BUYAYU', 'MAKANDWA CENTRAL', 'MAWOLOLO', 'NABWEYA', 'NAKAVULE'],
        'MAKUUTU': ['BUNALWENYI A', 'BUNALWENYI B', 'BUNALWENYI CENTRAL', 'BUSWIRIRI', 'BUWONGO', 'MAKUUTU', 'NAKADHULI'],
      },
      'NAMALEMBA': {
        'IDINDA': ['BULUGODHA', 'BUSWIIGA', 'IDINDA', 'NABIRERE A', 'NABIRERE B'],
        'MINANI': ['BUKAKAIRE', 'KITUKIRO', 'MINANI A', 'MINANI B', 'NABITENDE', 'NAKAMINI'],
        'NAMALEMBA': ['BUNIO', 'BUTAKANIRA', 'BUTONGOLE', 'NALWEGOLOIRE', 'NAWANGISA A', 'NAWANGISA B'],
        'NAMUNYUMYA': ['KINAMPERE A', 'KINAMPERE B', 'NAMUNYUMYA A', 'NAMUNYUMYA B'],
      },
    },
    'BUYENDE': {
      'BUGAYA': {
        'BUGAYA': ['BUGAYA T/CENTRE', 'BUGEMBE', 'BUKWAYA', 'BULINDA I', 'BULINDA II', 'BULINDA/BWASE', 'BUSEMBERA-BUTITI', 'BUWAIDHENO'],
        'BUSAABI': ['BEKULA T.C', 'BUGULUSI', 'BUKITIMBO', 'BUKOFU', 'BUKOLE', 'BUKOOSE', 'BULEGEYA A', 'BULEGEYA B', 'BUSAABI-BUBUGUDHO', 'BUWAZA', 'NALOOSE'],
        'BUTASWA': ['BUGWERI', 'BUKITIMBO', 'BUKOKOBA', 'BUKOSE', 'BUNYWANYI', 'BUWANGA', 'BUWELYA', 'KANYANGO', 'KAZIGO', 'NABIGWO', 'NAKAVUMA'],
        'IRAAPA': ['BUBALIYO A', 'BUBALIYO B', 'BUGUNDULYA', 'BUKELEMENTI', 'BULAGALA', 'BULUBAALE', 'BULUBAALE BUWAYA', 'BUWADAMU'],
        'KIGWERI': ['BUBANDA', 'BUKOSIYA', 'BUKYOMBA A', 'BUKYOMBA B', 'BUPENDO', 'BUSOBYA'],
        'NAMUKUNYU': ['BUDHUGU', 'BUDOOGO A', 'BUDOOGO B', 'BUGOBI', 'BUKANIFA', 'BULUNGU', 'BUSISIRO', 'BUSUSWA/BUKIIKA', 'BUSWANKAMA'],
        'NAMUSIKIZI': ['BUBANDA', 'BUKYELAGA', 'BUSAAMA A', 'BUSAAMA B', 'BUTUBI'],
      },
      'BUKUNGU TOWN COUNCIL': {
        'BUKUNGU WARD': ['BUZAAMA', 'KAPIOKOLO A', 'KAPIOKOLO B', 'KISOGA', 'KIWANTAMA', 'KIWANTAMA T/C', 'KYOGA A', 'KYOGA B', 'LUFULAKIKWATA', 'LUFUULA'],
        'KIBAALE WARD': ['BUDOOBA A', 'BUDOOBA B', 'KANGANYANZA', 'KANGANYANZA LANDING SITE', 'KINAMUWANGA A', 'KINAMUWANGA B', 'KINAWANKEMBO A', 'KINAWANKEMBO B'],
        'KYANKOOLE WARD': ['BUYANJA A', 'BUYANJA B', 'KYANKOOLE', 'KYANKOOLE LANDING SITE'],
      },
      'BUYANJA': {
        'BUTAYUNJWA': ['BUTAYUNJWA A', 'BUTAYUNJWA B', 'KABALONGO', 'KABALONGO T.C', 'KALUNGI', 'KIIGA', 'KIWONGOIRE A', 'KIWONGOIRE B'],
        'BUYANJA': ['KASAATO', 'NAWANSASO A', 'NAWANSASO B'],
        'NTAALA': ['KASAALA', 'NAKAWA A', 'NAKAWA B', 'NAKAWA C', 'NAKAWA TC', 'NTAALA', 'NTAALA TC'],
      },
      'BUYENDE': {
        'IKANDA': ['IGOMERO A', 'IGOMERO B', 'KALAMBO A', 'KALAMBO B', 'KIGANJA A', 'KIGANJA B', 'KIGANZA A', 'KISUYI', 'MAGOGO A', 'MAGOGO B', 'MUKUUMA T/C'],
        'KAKOOGE': ['KAKOOGE CENTRAL A', 'KAKOOGE CENTRAL B', 'KAKOOGE LANDING', 'KAKOOGE TC', 'KASOZI', 'KIKAAYA A', 'KIKAAYA B', 'MAILO A', 'MAILO B', 'NKOONA', 'RWOKO'],
        'KIRIBAIRYA': ['ISISI LANDING', 'KIBYASI', 'KIRIBAIRYA A', 'KIRIBAIRYA CENTRAL A', 'KIRIBAIRYA CENTRAL B', 'KIRIBAIRYA LANDING', 'KIRIBAIRYA T/CENTRE', 'WAIRUGALA'],
        'MANGO': ['BUGAGA A', 'BUGAGA B', 'BULUBA', 'BUSOBYA', 'KALIRO A', 'KALIRO B', 'KIRIMBI A', 'KIRIMBI B', 'NAKABEMBE A', 'NAKABEMBE B', 'NSONKO A', 'NSONKO B'],
        'NAMUSITA': ['IKOONA', 'KADEBEDE A', 'KADEBEDE B', 'KASULETA A', 'KASULETA B', 'NAMUSITA CENTRAL'],
      },
      'BUYENDE TOWN COUNCIL': {
        'BUMYUKA WARD': ['BUDUNGU', 'BUGASANI', 'BULOKE', 'BUMYUKA EAST', 'BUMYUKA WEST', 'BUNANGWE', 'BUTOOLI', 'BUWAIDHA'],
        'BUYENDE WARD': ['BUTAASA', 'BUYENDE TRADING CENTRE', 'DEMA', 'KISEEGE', 'NABUKALU'],
        'KINAMBOGO WARD': ['BUBALYA', 'BUNANTAMU', 'BUSAMBIRA', 'BUTAALU', 'BUWANDE', 'KANYANYAGO'],
        'MAKANGA WARD': ['BUBENGO', 'BUGOGO', 'BUKALIMO', 'BULUUBE', 'BUSEETE', 'BUSUUYI', 'BUWOIRA', 'MAKANGA T/C'],
        'NAKABIRA WARD': ['BUKONOKA', 'BUTANAABA/BUKEWA', 'KISEEGE', 'NAMAVUNDU/ITUBA', 'NAMBALE'],
      },
      'GUMPI': {
        'BUDOLA': ['BUNABALA', 'BUSULU', 'KIRONGO', 'KIRONGO T.C'],
        'GUMPI': ['BUDONGA', 'BUDOPE', 'BULEERO/BUZIBU', 'BUSIGE', 'BUSIKWE A', 'BUSIKWE B', 'BUSULEETA', 'BUSUMBA', 'GABULA'],
        'INNULA': ['BUDHATUMMU', 'BUKWAYA', 'BUKWAYA/BUTOOLI', 'BUKWAYA/BUTOOLI T.C', 'BUSINGA/BUDHATUMU', 'BUSUSWA', 'BUSUUBO', 'BUTOOLI', 'BUTOOLI/BUSUBO', 'BUTOOLI/BUSUSWA', 'INNULA T/C', 'INNULA-BUTOOLI'],
        'KIMBAYA': ['BUKALINAKI', 'BULANGIRA A', 'BULANGIRA B', 'BULODI', 'BUSIMBA', 'KIMBAYA', 'LUKOTAIME', 'NAKALAMA'],
        'KITUKIRO': ['BUDOOLI', 'BUGUNDHO/BUDOOLI', 'BUKANOBE', 'BULANGIRA', 'BUSUUSA', 'BUSUUSWA', 'BUWAIBUGA', 'KITUKIRO TRADING CENTRE', 'KYABAGOOLE', 'KYABAGOOLE-BUSAALA'],
        'NABITULA': ['BUBEKO', 'BUBEKO-BUGOLO', 'BUBIRO', 'BUDHONGA', 'BUGEMBE', 'BUKAMIRA', 'BUKIIKA', 'BUSANGA', 'BWOGEREZA'],
      },
      'IRUNDU': {
        'BUDIPA': ['BUDIPA I', 'BUDIPA II', 'BULUNDA', 'KASEKENYI', 'KIBUGO'],
        'BUKUTULA': ['BUGANZA', 'BUKUTULA', 'BULAGALA', 'BUNANGWE', 'BUSOOKO', 'MASABA', 'NADIOPE', 'NAKAWUNA'],
        'IGALAZA': ['BULONDO', 'BUTEIRA A', 'BUTEIRA B', 'IGALAZA', 'KINAMAIGA', 'MPUNDE A', 'MPUNDE B', 'NAKABEMBE A', 'NAKABEMBE B', 'NGEREKA'],
        'NKOONE': ['BUKYALA', 'BUPIOKO', 'BUTOOLI A', 'BUTOOLI B', 'NADIOPE/NAIKA', 'NAMALOGWE'],
      },
      'IRUNDU TOWN COUNCIL': {
        'BUGULUSI WARD': ['BUKOSI', 'BUSAMBA', 'KUBOTA A', 'KUBOTA B'],
        'IRUNDU WARD': ['BUKOKOLA A', 'BUKOKOLA B', 'BUKOKOLA C', 'BUKOKOLA D', 'IRUNDU A', 'IRUNDU B'],
        'KAGWA WARD': ['BBUDORYO A', 'BBUDORYO B', 'BULEMEZI A', 'BULEMEZI B', 'KAGWA A', 'KAGWA B'],
        'KANAKU WARD': ['BUTEGERE A', 'BUTEGERE B', 'BUTEGERE C', 'DONGI A', 'DONGI B', 'NAMUNYINGI'],
      },
      'KAGULU': {
        'BUMUGOLI': ['BUGALU', 'BUGULUSI', 'BULABE', 'BUSOLO', 'BUWALUKA', 'BUWANGA', 'KAMUGOYA', 'MAIRO', 'NAKAWOLO'],
        'BUYUMBA': ['BUYUMBA A', 'BUYUMBA B', 'IGWAYA', 'KITOIKI', 'NAMWIZUKYA'],
        'IYINGO': ['BULONGOOLI', 'IYINGO TOWN', 'KASANGA', 'KASOZI', 'NAGANGAMA A', 'NAGANGAMA B', 'NAKATWE'],
        'KABUKYE': ['BUGANIRA', 'BUNANGWE', 'BUSIGE', 'KABUKYE', 'KAMERI', 'KILIMBI', 'NABUKU A', 'NABUKU B', 'NGOLE'],
        'KAGULU': ['BULANGIRA', 'BUSUBO/MPANGA', 'BUTAKOMA', 'BUTEMEERA A', 'BUTEMEERA B', 'BUWERYA/BULUBA', 'GABONA', 'KIBIRA/KYEZA', 'MIRU', 'NALIINA'],
        'KIRIMWA': ['BUKONGORO', 'BULAYI A', 'BULAYI B', 'BUSUYI', 'KINAMAGIRA A', 'KINAMAGIRA B', 'KINATEBE A', 'KINATEBE B'],
        'MULALI': ['BUKOSE/BUNANGWE A', 'BUKOSE/BUNANGWE B', 'BULANGAIRE', 'BULUBA/BUWERYA A', 'BULUBA/BUWERYA B', 'BUTENDE/BULOBE'],
        'NSOMBA': ['BUGAGA A', 'BUGAGA B', 'BUGEMBE', 'BULUNGANA', 'BUSALWA', 'BUSUUBO-MPANGA', 'ITANINHI', 'KAKIRA'],
      },
      'KIDERA': {
        'BULEMBO': ['BUKANZA/BUNYONA', 'BULAMULI', 'BULEMBO/MEERU', 'BULINDA/MWIGA', 'BULINDI', 'KAKYANGA', 'KANYOGOGA', 'KIIKARA', 'MASEMBE', 'MEERU', 'NAKITUBA', 'NAWANSEGA'],
        'KASIIRA': ['KAMASIIRA', 'KASIIRA TC', 'KIRIMUNSEEGE', 'NAIROLWA'],
        'KISAIKYE': ['KISAIKYE', 'NAKIMUNKU', 'NFUMAGANI', 'NFUMAGANI NILE SHORES'],
        'MISERU': ['MATIKI A', 'MATIKI B', 'MISERU/MERU', 'NABIGWO', 'NAMBOLI I', 'NAMBOLI II'],
        'NDUDU': ['BUKAMBA', 'BUTOLI', 'MBIIKO TC', 'MIRENGEIZO A', 'MIRENGEIZO B', 'NDUDU'],
      },
      'KIDERA TOWN COUNCIL': {
        'ITAMIA WARD': ['BUGEZYA', 'BUZIMBA', 'KALAGALA', 'MERU', 'MERU KYOGA', 'MERU TRIANGLE', 'WALUMBE'],
        'KABUGUDHO WARD': ['GREEN ZONE', 'KABUGUDHO A', 'KABUGUDHO B', 'KABUGUDHO TRADING CENTRE', 'NABWEYO A', 'NABWEYO B', 'NAKABEMBE A', 'NAKABEMBE B'],
        'KIDERA WARD': ['BUNAKWITA', 'KAKIIKA', 'KIWAMBYA', 'KYAUKA', 'NGULAMUBIRI'],
        'KITAIDHUMBA WARD': ['KANANTEGE', 'KATOGWE A', 'KATOGWE B', 'KITAIDHUMBA A', 'KITAIDHUMBA B', 'MERU', 'NAKIBENGO'],
        'KITETE WARD': ['KAMAGO', 'KITAYUNJWA', 'KITETE A', 'KITETE B', 'KYANYONYI'],
      },
      'NDOLWA': {
        'BUTONGOLE': ['BUDUULI', 'BUGANZA A', 'BUGANZA B', 'BUKAMBI', 'BUSUBO I', 'BUTONGOLE I', 'BUTONGOLE II'],
        'NABIGAGA': ['BUGAVU', 'BULANGIRA', 'BULUBA I', 'BULUBA II', 'BUTABAZI', 'BUTEMAWA', 'BUYOKERO', 'NABIGAGA', 'NDOLWA TRADING CENTRE'],
        'NDOLWA': ['BULONDO', 'BULUUBE', 'BUSIKWE I', 'BUSIKWE II', 'KIGAYA', 'KISUUBO A', 'KISUUBO B', 'MASETE A', 'MASETE B', 'NDULYA/KISUUBO'],
        'WESUNIRE': ['BAGANZI', 'BAGANZI-NYUNDHO', 'BUSUBO II', 'BUSUBO III', 'IDALA-BUTATU', 'IDHAALA A', 'IDHAALA B', 'KISUUYI A', 'KISUUYI B', 'KIYUNGA A', 'KIYUNGA B'],
      },
      'NGANDHO': {
        'BUYAMBA': ['BUKWANGA/BUBBUPI', 'BUKWANGA/BUSANO', 'BUSUSWA BUBEKO', 'BUYAMBA A', 'BUYAMBA B'],
        'GWASE': ['BUBEEKO A', 'BUBEEKO B', 'BUGABO', 'BUGALAIRE', 'BUGULUSI/BUTALENGA', 'BULONDA', 'BUSERANDA', 'BUTADHI', 'BWOSI', 'KYABAZAALA'],
        'KIRIMBI': ['BUBANDA', 'BUDHUBULI', 'BUDHUMBULA', 'BUKWALU', 'BULUNGU/BUGAGA', 'KIRANGIRA'],
        'NABISIKI': ['BAGAYA-BULONDO', 'BUGAGA/BUSANO A', 'BUGAGA/BUSANO B', 'BUGANZA', 'BUGANZA/BUTOOLI', 'BUGOBI/BUSIKWE', 'BULANGIRA', 'BUSOBYA-BULONDO'],
        'NGANDHO': ['BUKOSE/BUGAYA A', 'BUKOSE/BUGAYA B', 'BUSEMBYA', 'BUSUUBO', 'KASINGA/GWALA A', 'KASINGA/GWALA B'],
        'WANDAGO': ['BUGE-BULONDO', 'BUGONDA-BUYINGO', 'BUGONDA/BUBBUPI', 'BUKOSE/BUGONZI', 'BUKOZA/BUWANDE', 'BULANDA-BUNABALA', 'BULANGIRA/BUWAYA', 'BUNHA/BUYEGA', 'BUSOOKO-BUGONZI', 'BUSOOKO/BUBAALE', 'BUSOOKO/BUGANDA', 'BUSUSWA/BUKWANGA'],
      },
      'NKONDO': {
        'IMMERI': ['IMMERI', 'IMMERI B', 'IMMERI C', 'NABIGWO', 'NANVUNANO', 'NANVUNANO CENTRAL'],
        'IRINGA EAST': ['IZUNGWE', 'KALOGOI', 'KALOGOI B', 'KIGEIZERE', 'KIGEIZERE B', 'NAKASEDHERE'],
        'IRINGA WEST': ['KABONGE', 'KASUKU A', 'KASUKU B', 'KISENKENYI', 'MANI A', 'MANI B', 'NAKAKABALA'],
        'KIGINGI': ['KABUGU', 'KANAMUZIGO', 'KASONGOIRE', 'KASONGOIRE B', 'KAYOMBO', 'LWEVOLA', 'NAMULANDA', 'NAWAMPITI'],
        'KIWABA': ['BUTIMBITO', 'KATEGANGO', 'KIRANGIRA', 'KIRIMIRA', 'LUKUTAIME', 'NABYEWANGA', 'NDYEMEIRE'],
        'MALIMA': ['BUSIGE', 'BUSIGE B', 'KALANGA', 'KIWOLOGOMA', 'KIWOLOGOMA B', 'NAWAIKIKI', 'NAWAIKIKI B'],
        'NDULYA': ['KAKOOGE', 'KIRIMBI', 'KYESIRIKIRE', 'KYOGA', 'NAKANSAGA', 'NDHWEDHWE', 'NDULYA/BUGABULA', 'TIIMI', 'WAKUKUTA'],
        'NSEKASEKA': ['KYABAZALA', 'KYANGUNDU', 'NABULAGALA', 'NAIBULUKA', 'NSEKANSEKA', 'NSEKANSEKA B'],
      },
    },
    'IGANGA': {
      'BULAMAGI': {
        'BUKOYO': ['BUDHWEGE', 'BUKABISI', 'BUKOYO', 'NAWANSINGE'],
        'BULAMAGI': ['BUBAKA', 'BULAMAGI'],
        'BULOWOOZA': ['BULOWOOZA', 'KASOLO', 'MADHIGANDERE', 'MAWOITO', 'NGANGALI', 'WALUKUBA'],
        'BWANALIRA': ['BUDHEBERA', 'BUWASA', 'BUYUBU', 'BWANALIRA', 'IGULAMUBIRI', 'KINAWANSWA'],
        'IWAWU': ['BUWOYA', 'IWAWU', 'KYEMEIRE', 'MASABA', 'NAMALEMBA', 'NAMASOGA', 'NAWANKOFU', 'NKAZIWERU', 'NTINDA'],
      },
      'CENTRAL DIVISION': {
        'BULIGO WARD': ['BULIGO NORTH', 'KASOKOSO NORTH', 'KASOKOSO SOUTH', 'KAYAGA'],
        'KASOKOSO WARD': ['KASOKOSO CENTRAL I', 'KASOKOSO CENTRAL II'],
        'NABIDONGHA PRISON WARD': ['BULIGO SOUTH', 'BULIGO SOUTH A', 'NABIDONGA C', 'NABIDONGHA PRISONS'],
        'NABIDONGHA WARD': ['NABIDONGHA A', 'NABIDONGHA B', 'NABIDONGHA PROPER'],
        'NAKAVULE WARD': ['LUBAALE', 'NAKAVULE \'A\'', 'NAKAVULE \'B\'', 'NAKAVULE MAIN'],
        'WALUGOGO WARD': ['KASOKOSO CENTRAL III', 'WALUGOGO HOUSING ESTATE'],
      },
      'KIDAAGO': {
        'KAZIGO': ['KAZIGO A', 'KAZIGO B'],
        'KIDAAGO': ['KIDAAGO A', 'KIDAAGO B'],
        'NABITENDE': ['BUKOSE ZONE', 'BUSABI ZONE', 'BUYALE ZONE', 'NABITENDE A', 'NABITENDE B'],
        'NAIBIRI': ['NAIBIRI CENTRAL', 'NAIBIRI NORTH', 'NAIBIRI SOUTH'],
      },
      'NABITENDE': {
        'BUGONO': ['BUGONO', 'BUGONO B', 'NABINONYI'],
        'ITANDA': ['BUKAIGO', 'BUVULE', 'ITANDA - BUWEIRA', 'KINU'],
        'KABIRA-ITUBA': ['BUIGANHA B', 'BULIGANHA', 'ITUBA A', 'ITUBA BUNIGULE', 'KABIRA A', 'KABIRA B'],
        'KASAMBIKA': ['BUWEREMPE', 'KASAMBIKA I', 'KASAMBIKA II', 'NAMUSIISI I', 'NAMUSIISI II'],
        'NABITENDE': ['BUBEKO', 'BUTABALA', 'KALUNGAMI \'A\'', 'KALUNGAMI \'B\'', 'NABITENDE'],
        'NALUKO': ['NALUKO', 'NALUKO BUZIBIRILA', 'NAWANKWALE', 'NAWANKWALE BUGWERE'],
      },
      'NAKALAMA': {
        'BUKAYE': ['BUKAYE', 'BUWONGO', 'IGULUSA', 'NAMPIRIKA A', 'NAMPIRIKA B'],
        'BUKOONA': ['BUKALAMBWA', 'BUPALA', 'KAKONGOKA', 'KAKONGOKA B', 'NAMUNDUDI A', 'NAMUNDUDI B', 'NAMUNDUDI C'],
        'BUSEYI': ['BUSEYI A', 'BUSEYI B', 'BUSEYI CENTRAL'],
        'NAKALAMA': ['BUKOBOOLI', 'BUKYAYE', 'BUTAAMA', 'NABIRYE', 'NAKALAMA CENTRAL', 'NAKALAMA NORTH', 'NAKALAMA SOUTH'],
      },
      'NAKIGO': {
        'BULUBANDI': ['BUGABWE', 'BULUBANDI CENTRAL A', 'BULUBANDI CENTRAL B', 'NANDEKULA A', 'NANDEKULA B'],
        'BUNYAMA': ['BUKWAYA', 'BUNYAMA', 'KIBOYO', 'NAMIRALI'],
        'BUSOWOOBI': ['BUSOWOOBI CENTRAL', 'BUSOWOOBI- NYENGA', 'KIWERERE', 'NABITOVU', 'NAKIGO I', 'NAKIGO II'],
        'KABIRA': ['BULUZA', 'KABIRA', 'NAMUSENWA', 'NAWANZU'],
        'WAIRAMA': ['IZIMBA', 'KAKOMBO', 'NAKISENYI', 'WAIRAMA'],
      },
      'NAMBALE': {
        'MWIRA': ['KAMIRABIKOMO', 'MWIRA', 'NABITOVU', 'NABITOVU NORTH'],
        'NAMBALE': ['NAMBALE I A', 'NAMBALE I B', 'NAMBALE II'],
        'NASUTI': ['BUSIMBA', 'KAKIRA', 'NABUKONE', 'NASUUTI NORTH', 'NASUUTI SOUTH'],
      },
      'NAMUNGALWE TOWN COUNCIL': {
        'BULUMWAKI WARD': ['BULUMWAKI I', 'BULUMWAKI II', 'NSINZE'],
        'MWENDANFUKO WARD': ['BULANGA', 'MWENDANFUKO'],
        'NAMUNGALWE WARD': ['KAWETE', 'NAMUNGALWE A', 'NAMUNGALWE B', 'NAMUNGALWE RURAL'],
        'NAMUNKANAGA WARD': ['NAMUNKANAGA I', 'NAMUNKANAGA II'],
        'NAMUNKESU WARD': ['BUBOGO A', 'BUBOGO B', 'NABIKOOTE', 'NAMUFUMA', 'NAMUNKESU'],
        'NAMUNSAALA WARD': ['BUFUTULA A', 'BUFUTULA B', 'NAMUNSAALA'],
        'NAWANSEGA WARD': ['NAWANSEGA A', 'NAWANSEGA B'],
      },
      'NAWANDALA': {
        'BUGONGO': ['BUGOLE A', 'BUGOLE B', 'BUGONGO', 'BUGONGO B', 'BUSAKAIRE', 'NAMABWERE I', 'NAMABWERE II', 'NAMUKUMYA', 'NAWANDALA', 'NAWANGAIZA II'],
        'KIWANYI': ['BUKYEEGA', 'BUSAALA', 'BUWUMBA', 'KIWANYI I', 'KIWANYI II', 'MADHIMASU'],
        'KYENDABAWALA': ['BUGAMBO', 'BUNYOKANO', 'BUSOIGI', 'BUZAAYA', 'IKUMBYA', 'KABULI I', 'KABULI II', 'KYENDABAWALA'],
        'NAMUSIISI': ['BUGANZA', 'BUYUNGA', 'MALOBI', 'NAMUSIISI'],
        'NAWANGAIZA': ['KIRINGA A', 'KIRINGA B', 'NAWANGAIZA I'],
      },
      'NAWANYINGI': {
        'BUNYIRO': ['BUKOSE', 'BUNYIIRO', 'BUWOLOMER B', 'BUWOLOMERA A', 'LWABAGA', 'NAGADUDULA'],
        'MAGOGO': ['BUKONKO', 'BUWANDE', 'BUWENDA', 'LWERERA', 'MAGOGO', 'NAKIRULWE', 'NAWANDYO'],
        'NAWANYINGI': ['BUWOIREKU', 'LUGOBANGO', 'MAWAGALA', 'MBAALA', 'NAWANKONGE', 'NAWANYINGI', 'WALUGOMA'],
      },
      'NORTHERN DIVISION': {
        'BUGUMBA WARD': ['BUGUMBA A', 'BUGUMBA B', 'BUGUMBA CENTRAL', 'BUGUMBA UPPER'],
        'IGAMBA WARD': ['BIKADHO', 'IGAMBA', 'IGAMBA SOUTH'],
        'MUTUKULA WARD': ['MUTAMBALA', 'MUTUKULA', 'NKONO I', 'NKONO III'],
        'NKATU WARD': ['KILOWA', 'NKAATU MAIN', 'NKAATU PROPER'],
        'NKONO WARD': ['NKONO CENTRAL', 'NKONO II', 'SILIVE'],
      },
    },
    'JINJA': {
      'BUSEDDE': {
        'BUGOBYA': ['BUGAYA', 'BUGOBYA', 'BULAKABYA', 'BULONDO', 'LUKONKO', 'NABIRAMA', 'NAKATI', 'NAMAZALA', 'NANFUGAKI', 'NYENGA'],
        'ITAKAIBOLU': ['BUGONGOLO', 'ITAKAIBOLU', 'KALIRO/BUPUPA', 'KASITA', 'KASOZI', 'KIGALAGALA', 'MPAMBWE', 'NAMATOLO', 'WALUMBUGU'],
        'KISASI': ['BULINDA', 'IRERA', 'KAKUBA', 'KATALAKABI', 'KISASI', 'NABULAGALA', 'NAKABALE', 'NAMAGANGA', 'NAMAZINGIRI', 'NKALANGE'],
        'NABITAMBALA': ['BUSIGE', 'BUWOLOMERA', 'BWIDHABWANGU', 'IRONGO', 'ITENGEZA', 'KISIRIRA', 'NABITAMBALA', 'NABIWAWULO', 'WANTUNDA'],
        'NALINAIBI': ['BUDHOOMA', 'KANAMA', 'KIKO', 'KINABIRYE', 'LWINO', 'NALINAIBI', 'NTINDA'],
      },
      'BUTAGAYA': {
        'BUDIMA': ['BITULI', 'BUDIMA', 'BUWUMA EAST', 'BUWUMA WEST A', 'BUWUMA WEST B', 'KABEMBE EAST', 'KABEMBE WEST', 'KIWAGAMA NORTH', 'KIWAGAMA SOUTH', 'NAKASEGETE'],
        'NAKAKULWE (KISOZI)': ['BUWALA A', 'BUWALA B', 'BUWALA C (ITANDA)', 'IWOLOLO  B', 'IWOLOLO A', 'KISOZI A', 'KISOZI B', 'LUMULI A', 'LUMULI B', 'LUMULI C', 'LUMULI KALUGU D', 'NAKAKULWE A', 'NAKAKULWE B'],
        'NAWAMPANDA': ['BUBUGO BUGOBI', 'BUBUGO BULONDO', 'BUBUGO CENTRAL', 'BULONDO A', 'BULONDO B', 'BUSOWOOKO B', 'BUSOWOOKO CENTRAL', 'BUWOLOMERA', 'BWEIGAMYE', 'NABUKOSI BUGAISO A', 'NABUKOSI BUGAISO B', 'NABUKOSI CENTRAL', 'NAWAMPANDA CENTRAL'],
        'WANSIIMBA': ['BUTAGAYA BWASE', 'BUTAGAYA WAIBUGA', 'KIRANGA BUFUTA', 'KIRANGA BUSOOBA', 'KIRANGA BUSUSWA A', 'KIRANGA BUSUSWA B', 'KITENGESA BUGERERE', 'KITENGESA MPEMUKIRABUSA', 'WANSIMBA NAKABBALE', 'WANSIMBA NAMAVUNDU'],
      },
      'BUWENGE': {
        'BUWEERA': ['BUWEERA EAST', 'BUWEERA WEST', 'BUWOLERO CENTRAL', 'BUWOLERO IGOMBE', 'BUWOLERO KIZINGA', 'BUWOLERO MAWOLERO', 'BUWOLERO NAKULYAKU', 'YUUKA'],
        'KAGOMA': ['KAGOMA BUWOLOMERA', 'KAGOMA CENTRAL', 'KAGOMA MAKOTA', 'MUTAI BUSIBE', 'MUTAI CENTRAL', 'MUTAI KANYALE', 'NAMALERE CENTRAL', 'NAMALERE KABAGANDA', 'NAMALERE SOUTH'],
        'KAIIRA': ['BUTEGANA EAST', 'BUTEGANA WEST', 'KAIIRA', 'MAWOITO BUBIRO EAST', 'MAWOITO BUBIRO WEST', 'MAWOITO BUKOLOKOTI', 'MAWOITO BUKYEBAMBE', 'MAWOITO BUYEMBA', 'MAWOITO KIGAYA', 'MUWANGI BUKOLWA', 'MUWANGI BULAGALA', 'MUWANGI BULUMBA'],
        'KITANABA': ['BUSIA II', 'IDOOME', 'ISIRI', 'KITANABA', 'MPUNGWE'],
        'MAGAMAGA': ['BUTANGALA A', 'BUTANGALA B', 'BUTANGALA C', 'BUTANGALA D', 'IGOMBE BULAGALA', 'IGOMBE BUSIGE', 'KALEBERA EAST', 'KALEBERA WEST', 'KYERINDA SOUTH', 'MAGAMAGA EAST', 'MAGAMAGA WEST', 'MUGULUKA EAST', 'MUGULUKA WEST'],
      },
      'BUWENGE TOWN COUNCIL': {
        'KAGAIRE WARD': ['HOSPITAL ZONE', 'KALAMOYA ZONE', 'MUHOFA ZONE', 'MUKWANGA ZONE', 'WAMUKOLO ZONE'],
        'KALITUNSI WARD': ['BUDHUMBULI ZONE', 'BUSIA ZONE', 'KILANGIRA ZONE', 'SWANU ZONE'],
        'KAMWANI WARD': ['BWASE', 'CHURCH ZONE', 'KABI ZONE', 'MUZIGITI ZONE'],
        'KASALINA WARD': ['KADIBA ZONE', 'KIGENYI ZONE', 'KYERINDA ZONE', 'MARKET ZONE', 'MUNYEGERA ZONE'],
      },
      'BUYENGO TOWN COUNCIL': {
        'BULUGO WARD': ['BUDHOBYA CELL', 'BULAMA A', 'BULAMA B', 'BUSEGULA', 'KAYALWE A', 'KAYALWE B', 'LWANYAMA', 'NAKITOKOLO'],
        'BUTAMIRA WARD': ['BUBANDA', 'BUGONGWE', 'BUKOLOBOZA', 'KITUMBUGULU', 'LWITAMAKOLI', 'MUSISI', 'NAMATA', 'NAWAMBOGA'],
        'BUWABUZI WARD': ['BUDAALI', 'BUWABUZI', 'BUYENGO', 'KAMIIGO', 'KANGULUMIRA', 'LWAMBOGO', 'NABIGWALI', 'NAKIVUMBI', 'NAMISOTA'],
        'IZIRU WARD': ['BALIBONA', 'BUDHUMBULU', 'BUKASAMI', 'BUKYEYUNE', 'BUYONGO', 'MBAALE CELL', 'NABITOSI', 'NABULAGALA', 'NABUSAGWA', 'NAKAJO'],
      },
      'KAKIRA TOWN COUNCIL': {
        'CHICO WARD': ['BATI SAFI', 'KAGOMA GATE', 'KALANTIN', 'KYENDA', 'MATAFALI'],
        'KABYAZA WARD': ['KABYAZA', 'LINE KUBWA', 'LINE MABATI', 'LINE RAILWAY', 'LINE SAMIA', 'LINE SECURITY', 'LINYA'],
        'KAKIRA WARD': ['BANGALOW', 'GO MOJA', 'KHAT/KASABA', 'KIRINYA', 'KOROKOTO', 'LAND/KATOOKE', 'MAJIMAZULI', 'MUTAI', 'NTINKALU', 'NYANZA QUARTER', 'SINGLE QUARTER', 'TEREGO', 'WELFARE/STAFF QUARTERS'],
        'MAWOITO WARD': ['KABEMBE A', 'KABEMBE B', 'KAGOGWA', 'MAWOITO A', 'MAWOITO B'],
        'MWIRI WARD': ['BUSOGA COLLEGE MWIRI', 'KINYORO-KITESO', 'MWIRI PRIMARY SCHOOL', 'NAKIGO', 'NAMAZIBA', 'WAIRAKA B'],
        'POLOTA WARD': ['DUMBA', 'MARKET', 'NALONGO', 'POLOTA A', 'POLOTA B', 'SCHOOL'],
        'WAIRAKA WARD': ['NALUBAALE', 'WAIRAKA A', 'WAIRAKA CENTRAL', 'WAIRAKA COLLEGE', 'WALUMBE'],
      },
      'NAMAGERA TOWN COUNCIL': {
        'LUBANI WARD': ['KIBUNDAIRE BUDHAGA', 'KIBUNDAIRE BUKWANGA', 'KIBUNDAIRE BUSEMBYA', 'LUBANI CENTRAL', 'LUBANI WEST'],
        'MPUMWIRE WARD': ['KIWUMO', 'KYEBANDO', 'MPUMWIRE CENTRAL', 'NAWAGUMA A', 'NAWAGUMA B'],
        'NAMAGERA WARD': ['BUGUMIRA A', 'BUGUMIRA B', 'KAMIRA', 'LUBIRA', 'MABIRA', 'NAMAGERA CENTRAL'],
        'NAMWENDWA WARD': ['NAMWENDWA A', 'NAMWENDWA B', 'NAMWENDWA C', 'NDIWANSI', 'NVUNWA'],
      },
    },
    'JINJA CITY': {
      'JINJA NORTH DIVISION': {
        'BUDHUMBULI EAST WARD': ['CHURCH ZONE', 'COMMERCIAL ZONE'],
        'BUDHUMBULI WEST WARD': ['KALINA ZONE', 'SCHOOL ZONE'],
        'BUWAGI (KAKYOMYA) WARD': ['BULEEBA', 'BUWAGI', 'IBBUNGU EAST', 'IBBUNGU WEST', 'KAGERA CENTRAL', 'KAGERA KIDIOPE', 'KAGERA VALLEY', 'KYOMYA CENTRAL', 'KYOMYA EAST', 'KYOMYA WEST'],
        'BUWEKULA WARD': ['BUWEKULA', 'KAINOGOGA', 'MAUTA', 'WAKITAKA'],
        'BUWENDA TC WARD': ['BUTIKI KYEKIDDE', 'BUTIKI MATAALA', 'BUWENDA CENTRAL', 'BUWENDA KYEKIDDE', 'BUWENDA MATAALA', 'IDHOGOLO', 'KAITABAWALA', 'WAKALENGE'],
        'IVUNAMBA WARD': ['BUDHAGALI', 'IVUNAMBA', 'KAZINGA', 'KIVUBUKA A', 'KIVUBUKA B', 'KYABIRWA'],
        'KATENDE WARD': ['IGENGE HILL', 'STADIUM', 'TRIANGLE ZONE'],
        'KIBIBI WARD': ['BUKOSE', 'BUSUSWA', 'BUWAIRAMA', 'BWASE A', 'KIZINGA', 'NAKANYONYI', 'NAMALEMBA'],
        'MAFUBIRA WARD': ['KAYUNGA', 'KITOVU', 'KYAMAGWA', 'MAFUBIRA A', 'MAFUBIRA B', 'MAFUBIRA C', 'MAKENKE', 'SAKABUSOLO'],
        'NAKANYONYI WARD': ['KATWE', 'NAKANYONYI ANNEX', 'NAKANYONYI BUKWARE', 'NAKANYONYI COMPLEX'],
        'NAMIZI WARD': ['BUYALA A', 'BUYALA B', 'BUYALA C', 'BUYALA TRADING CENTRE', 'KABOWA KAMPALA', 'KABOWA TRADING CENTRE', 'NAMIZI CENTRAL', 'NAMIZI EAST', 'NAMIZI WEST'],
        'NAMULESA WARD': ['ISUKWE', 'KAGOGWA', 'LWANDA', 'NAKABANGO', 'NAMULESA', 'WABULENGA A', 'WABULENGA B'],
        'NAWANGOMA WARD': ['BUFUULA A', 'BUFUULA B', 'LUKOLO EAST', 'LUKOLO WEST', 'NAWANGOMA', 'NSUUBE'],
        'WANYAMA WARD': ['CENTRAL CELL', 'EASTERN CELL', 'KATAMBA', 'MUTEKANGA'],
        'WANYANGE WARD': ['KALUNGAMI', 'MUSIIMA', 'WANYANGE CENTRAL', 'WANYANGE GIRLS', 'WANYANGE HILL', 'WANYANGE LAKE'],
      },
      'JINJA SOUTH DIVISION': {
        'CENTRAL JINJA EAST WARD': ['ALIDINA', 'IGANGA ROAD', 'KIRINYA ROAD', 'LUBAS ROAD', 'MAIN STREET EAST', 'OBOJA ROAD', 'SPIRE ROAD'],
        'CENTRAL JINJA WEST WARD': ['GABULA', 'MAIN STREET WEST', 'RIPPON GARDEN NILE AVENUE'],
        'KIMAKA WARD': ['AMBERCOURT', 'KIMAKA'],
        'LUBAGA WARD': ['COMMERCIAL', 'KAMULI ROAD', 'RUBAGA', 'UPLAND'],
        'MAGGWA WARD': ['GOKHALE', 'MADHIVANI', 'MVULE', 'NIZAM'],
        'MASESE WARD': ['KILEMBE', 'KISIMA I', 'KISIMA II', 'LWABITOOKE', 'MASESE I', 'MASESE II/DANIDA', 'MASESE III'],
        'MPUMUDDE WARD': ['MARKET ZONE A', 'MARKET ZONE B', 'NATIONAL HOUSING', 'WEST ZONE A', 'WEST ZONE B', 'WEST ZONE C'],
        'NALUFENYA WARD': ['NALUFENYA A', 'NALUFENYA B'],
        'OLD BOMA WARD': ['GRANT ROAD', 'KIRINYA PRISON', 'KYAGWE', 'LOCO', 'NILE CRESCENT', 'RIPPON FALLS'],
        'WALUKUBA EAST WARD': ['CENTRAL', 'CHURCH', 'NTEGE', 'POLICE WING', 'SCHOOL', 'STEEL'],
        'WALUKUBA WEST WARD': ['BABU', 'FACTORY', 'JROP', 'KLMN', 'MATERNITY', 'RAILWAYS', 'WORKS', 'ZABEF'],
      },
    },
    'KALIRO': {
      'BUDOMERO': {
        'BUDOMERO': ['BUGABWE-KASOZI', 'BUGABWE-NGOVA', 'BULANGIRA', 'BULEMO NANSINDO', 'KAHANGO', 'NABINYONYI', 'NAIRIKA T/C', 'NAIRIKA/KABULI', 'NAIRIKA/NAMUZIGO', 'NALUSENYE', 'NAMUKAKALA I', 'NAMUKALALA II', 'NAZIGOMERE'],
        'KIYUNGA': ['BAGOLE', 'BUKYESA A', 'BUKYESA B', 'BUSALAMUKA', 'BUSEREKA', 'NAKIBUNGULYA', 'NAMUZIGO'],
        'KYANFUBA': ['BUKERE I', 'BUKERE II', 'BUKULIRA', 'KANANSUNA/KISIKI', 'KANANSUNA/KYANFUBBA', 'LUGINGO', 'LUGONGO-KISENYI', 'LUMBUYE-KANANSUNA', 'NABWENDE', 'NAMUZIGO/BUDAMBA'],
        'NABITENDE': ['BUGADA', 'KIGOODO', 'NABITENDE', 'NABUKALU', 'NAMAKUNYU', 'NAMAVUNDU A', 'NAMAVUNDU B'],
      },
      'BUKAMBA': {
        'BUJUGU': ['ISOOBA', 'KANABI A', 'KANABI B', 'KISU B', 'KITENGA A', 'KITENGA B'],
        'BUKAMBA': ['BEEDA A', 'BEEDA B', 'BUKAMBA A', 'BUKAMBA B', 'LWAMBA A', 'LWAMBA B', 'LWAMBA C'],
        'BUSEREKA': ['BUGALIMU', 'BUGOLYO', 'BUSEREKA', 'KISANGA', 'KUNYA', 'KYAKYAMPASA A', 'KYAKYAMPASA B'],
        'BUVULUNGUTI': ['BUVULUNGUTI', 'BUVULUNGUTI EAST', 'BUVULUNGUTI WEST', 'BUZAAYA A', 'BUZAAYA B', 'KIBUYE A', 'KIBUYE B', 'KIBUYE C', 'KIBUYE D'],
        'KITEGA': ['BUKUNYA A', 'BUKUNYA B', 'BUNENE', 'KASULETA A', 'KASULETA B', 'KITEGA A', 'KITEGA B', 'NABUSIRA A', 'NABUSIRA B', 'NAKIBUNGULYA A', 'NAKIBUNGULYA B'],
        'NANGALA': ['BUZINGE T/C', 'KISU A', 'KUUTO A', 'KUUTO B', 'MUTUMIZI', 'MUTUMIZI A', 'MUTUMIZI B'],
        'NAWAMPITI': ['KABOLE', 'KAGWA', 'KISIRA', 'LUGONYOLA', 'LUGONYOLA B', 'LYADA', 'NDOLI', 'NDOLI B', 'SEMUTEWO', 'WALULALO', 'WOIRA'],
      },
      'BULUMBA TOWN COUNCIL': {
        'BUJJEJJE WARD': ['BAGALAMA', 'BUJEJJE', 'BUKUNYA', 'BULOMA', 'BUSIKWE', 'LUMBUYE'],
        'BULUMBA CENTRAL WARD': ['BUGUBI', 'BUKALIMO', 'BUKALIMO MAIN', 'BULONDO', 'MUKASA'],
        'BUSUNGA WARD': ['BUMPI', 'BUSUNGA', 'BWISOBA'],
        'LONDE WARD': ['KOSAMU', 'LONDE A', 'LONDE B', 'ZEFANIA A', 'ZEFANIA B'],
        'MASUNA WARD': ['BUMPULI', 'MASUNA', 'WANKESA'],
        'NALENYA WARD': ['BUNOGA', 'BUTITI', 'NALENYA I', 'NALENYA II', 'NATOLOKA'],
        'NKONTE WARD': ['BAGOLE', 'BULANGILA', 'BULEJU', 'BULIMUKA A', 'BULIMUKA B', 'BUNABALA', 'BUSUSWA'],
      },
      'BUMANYA': {
        'BULIMA': ['BULIMA', 'BULOMA I', 'BULOMA II', 'KASOZI', 'KIMUNYAGIRE', 'NAIGAZI', 'WAKIRERE'],
        'BUMANYA': ['BULUMI', 'GENDWA I', 'GENDWA II', 'LUGINGO', 'LUGINGO B', 'MAWULIRO', 'NABWEYO', 'NAMBULA/NABUKALU', 'WAMUBIRIGWE', 'WEMPERE'],
        'KALALU': ['KABIRI A', 'KABIRI B', 'KALALU I', 'KALALU II', 'KALALU III', 'KANAMBATIKO', 'KANANSEGA A', 'KANANSEGA B', 'KANANTALE', 'NAMUZIGO A', 'NAMUZIGO B'],
        'KASULETA': ['KASULETA', 'NABIGWALI I', 'NABIGWALLI II', 'NAIGAZI', 'TAKIRA CENTRAL', 'TAKIRA I', 'TAKIRA II', 'TAKIRA III'],
        'KYANI': ['KANANZOKI', 'KINAMAGOYE', 'KISENYI', 'KYANI - NYANZA B', 'KYANI T/C', 'KYANI/NYANZA A', 'NAIBINGA', 'NAKABALE', 'NAMBULA'],
        'NAMUSOLO': ['BUBBUMBI', 'IHAGALO', 'IHAGALO B', 'KIYUNGA', 'NAMBULA', 'NAMUNYA A', 'NAMUNYA B'],
      },
      'BUYINDA': {
        'BUKONDE': ['BUDABA', 'BUKONDE A', 'BUKONDE B', 'BUKONDE C', 'KIBUYE A', 'KIBUYE B'],
        'BUYINDA': ['BULAGO A', 'BULAGO B', 'BUTONGOLE', 'MAKUUTU', 'NABIINA A', 'NABIINA B'],
        'KIRANGA': ['KIRANGA A', 'KIRANGA B', 'KIRANGA C', 'KIRANGA TOWN', 'NAMUNINGE'],
        'MADIBIRA': ['KASULETA', 'KIKOOGE A', 'KIKOOGE B', 'KIRAMA A', 'KIRAMA B', 'MADIBIRA A', 'MADIBIRA B', 'NAMAYOBYO'],
        'NAMEJJE': ['KEREBU A', 'KEREBU B', 'NAMEJJE A', 'NAMEJJE B', 'NAMEJJE C'],
      },
      'GADUMIRE': {
        'BUPYANA': ['BUKERE', 'BUVUNDYA', 'KIRANGA A', 'KIRANGA B', 'KYAMBA', 'NAMUKOKO', 'NANSOHERA A', 'NANSOHERA B'],
        'BUTAMBALA': ['BUBALALA', 'BUDONGO', 'BUSERU', 'BUTAMBALA', 'IREHE', 'NAKAWA'],
        'BUYUGE': ['BUWUMBA', 'KABWIKWA/KABEGA', 'KAYIIRA A', 'KAYIIRA B', 'NAKANA'],
        'GADUMIRE': ['BUGADA/BUSEREKA', 'BUGONYA', 'BUNABIRO', 'BUSUSWA', 'GADUMIRE TRADING CENTRE', 'NABWEYO', 'WAMUSUTA'],
        'ISALO': ['BUSEETA', 'BUSIGINYI', 'BUTWOOLI', 'BWISANGA', 'ISAALO', 'LUHUNGA'],
        'PANYOLO': ['BUSEEGE', 'BUSIRO', 'BUSIRO CENTRAL', 'BUSIRO TABINA', 'IGULILYO', 'LAKE NAKUWA', 'NAKISENYI', 'NYOLO'],
        'TABABA': ['BUKOOTI', 'KIBEMBE', 'KIBEMBE B', 'MULUNGU', 'NAMUHONDO', 'NANSIONO', 'NASERE'],
      },
      'KALIRO TOWN COUNCIL': {
        'BUDINI WARD': ['BUDINI A', 'BUDINI B', 'BUDINI C', 'MISSION A', 'MISSION B', 'MISSION C', 'NYANZA A', 'NYANZA B'],
        'BUKUMANKOOLA WARD': ['BRIGHT FUTURE', 'BUGOMA A', 'BUGOMA B', 'BUGOMA C', 'BUKADAMA', 'BUKAVIRI', 'KIRINDI A', 'KIRINDI B', 'MWANGHA A', 'MWANGHA B'],
        'BUYUNGA WARD': ['BUSOMA A', 'BUSOMA B', 'BUWALUJJO', 'IGOMBE LUBOWA', 'MUKUNGU', 'NAKABALE', 'NAKIYANJA A', 'NAKIYANJA B', 'NAKIYANJA C', 'PALISA ISMA'],
        'LUMBUYE WARD': ['INDUSTRIAL AREA A', 'INDUSTRIAL AREA B', 'INDUSTRIAL AREA C', 'INDUSTRIAL AREA D', 'KALITUNSI A', 'KALITUNSI B', 'KALITUNSI C', 'VALLEY HILL A', 'VALLEY HILL B', 'VALLEY HILL C', 'VALLEY HILL D'],
        'NAIGOMBWA WARD': ['BUGABWE A', 'BUGABWE B', 'BULANGIRA A', 'BULANGIRA B', 'ZIBONDO A', 'ZIBONDO B'],
      },
      'KASOKWE': {
        'BUSANDA': ['BULANGIRA', 'BUSANDA', 'BUSANDA B', 'BUSANDA C', 'MAKERE'],
        'BUTAJJUBE': ['BUKAKUBBE', 'BUTUJU', 'BUYIGANGAINE', 'KALALU', 'NAKABALE'],
        'BUYODI': ['BUNAITA-BUJJOGO', 'BUTONGOLE', 'BUYODI/KIBOYO', 'KIRUMBI-KIBWANGUSHO', 'NAKYAATO'],
        'BWAYUYA': ['BUTESA A', 'BUTESA B', 'BWAYUYA A', 'BWAYUYA B', 'BWAYUYA C', 'BWAYUYA TRADING CENTRE'],
        'KASOKWE': ['BUGOODO', 'BUKONGOLO', 'BUSIBA', 'BUYODI KINANTAMA', 'KASOKWE T/C', 'KASOKWE/KIBOYO', 'NKALU A', 'NKALU B'],
      },
      'KISINDA': {
        'BUSULUMBA': ['BUKAYALE A', 'BUKAYALE B', 'BUTANGA', 'KYONAMUSA', 'NAKIKONDO', 'NAMUMBYA', 'NANTAHAYA', 'NYENDE'],
        'KIBWIZA': ['KAMUTAKA', 'KIBEMBE A', 'KIBEMBE B', 'KIBWIIZA', 'KIBWIIZA B', 'NAKAKOOGE'],
        'KISINDA': ['BUHOMBI', 'BUKUNYA', 'BUKUNYA TRADING CENTRE', 'NAKABOKO', 'NAMUNTU', 'NAMUTABA', 'NSULUMBI'],
        'LUBULO': ['KIBAALE A', 'KIBAALE B', 'MAHUMO A', 'MAHUMO B', 'NAMASAKA A', 'NAMASAKA B'],
        'MPAMBWA': ['LWAMBOGA A', 'LWAMBOGA B', 'MPAMBWA A', 'MPAMBWA B', 'NANDERE A', 'NANDERE B'],
        'NAWANDYO': ['BULEEMO', 'IGEMBE', 'KIROBA', 'NAWANDYO'],
      },
      'NAMUGONGO': {
        'BUGODA': ['BUGODA', 'BUTINDA', 'KALUNGU', 'KASOZI', 'KASULETA'],
        'BUGONZA': ['BUDANGHA/BULALA', 'BUHODI', 'BUKONGOLE', 'NABIRERE', 'NAKALANGA'],
        'BUTEGE': ['KANATEGE A', 'KANATEGE B', 'KITALIKIKYO', 'NAKISENYI', 'WAKUKUUTA', 'WAKUKUUTA B'],
        'IGULAMUBIRI': ['IGULAMUBIRI A', 'IGULAMUBIRI B', 'NABINYONYI A', 'NABINYONYI B', 'NAKABALE'],
        'KANAKAMBA': ['BUHULULAIRE A', 'BUHULULAIRE B', 'BULOGO', 'BULYANKOKO', 'BUSOOBA'],
        'NABIKOLI': ['BUKULABWIRE A', 'BUKULABWIRE B', 'KAJANABULWAIRE A', 'KAJANABULWAIRE B', 'LUMBUYE', 'NAMAKANDA A', 'NAMAKANDA B'],
        'NAMUKOGE': ['BUKIGIKI A', 'BUKIGIKI B', 'NAKYERE A', 'NAKYERE B', 'NAMUKOOGE T/C', 'SIRIKA'],
        'NATWANA': ['BULONDO/BUBONGO A', 'BULONDO/BUBONGO B', 'N.T.C KALIRO', 'NATWANA A', 'NATWANA B', 'NYALINYALI A', 'NYALINYALI B'],
      },
      'NAMWIWA': {
        'KIGANDA': ['IZINGA A', 'IZINGA B', 'KIGANDA A', 'KIGANDA B', 'KITUKIRO'],
        'KIWANABUZI': ['KIWA A', 'KIWA B', 'NABUZZI', 'NAWANGOMA A', 'NAWANGOMA B'],
        'NAMWIWA': ['BULUGULI', 'BUSAMBEKO A', 'BUSAMBEKO B', 'NAMUGERA', 'NAMWIWA B'],
        'SAAKA': ['BUGUGE', 'BUKEREHE', 'BWISANGA', 'IGEREKA', 'KAKOSI A', 'KAKOSI B', 'KAKOSI C', 'SAAKA A', 'SAAKA B'],
      },
      'NAMWIWA TOWN COUNCIL': {
        'BILARI WARD': ['BIRALI', 'BULUUKO', 'KAVULE A', 'KAVULE B', 'NAMULUNGU TC', 'NAWANGOMA'],
        'BUKAIRE WARD': ['BUKAIRE A', 'BUKAIRE B', 'BUKUNYA', 'KANABUGO B'],
        'BUNSWEZYA WARD': ['BUNSWEZYA', 'BUTENDE', 'MUTOME', 'NAKWANGALA A', 'NAKWANGALA B'],
        'BUSEREKA WARD': ['BAZIRABAIRA', 'BUGOBOLO', 'BUSEREKA A', 'BUSEREKA B', 'MUGIRE'],
        'KANABUGO WARD': ['KANABUGO A', 'KATALAKABI', 'TALINA', 'WAMPITEKU', 'WANGOBO B'],
        'NAMWIWA WARD': ['BAGANZI', 'GABWIIRE', 'MUTENDERI', 'NAMWIWA A'],
        'WANGOBO WARD': ['BUNGUBEKA', 'NABUHALI', 'WANGOBO A', 'WANGOBO C'],
      },
      'NANSOLOLO': {
        'BULIKE': ['BUBWIIKA', 'BUDEEBA A', 'BUDEEBA B', 'BUKOMAHO', 'NZIRAKAYINDI A', 'NZIRAKAYINDI B'],
        'BULUYA': ['AZALIYA BALISULEYO', 'BALISULEYO', 'BULAWA', 'BUNANGWE', 'BUSUSWA', 'KOSIYA KALUYA', 'KYALIZWANYUMA', 'PEREZI KASAJJA'],
        'MUHIRA': ['BULUYA II', 'BUSENKE', 'IKONERO', 'ISOOBA MALE', 'KIHOLERE', 'MULI I', 'MULI I T/C', 'MULI II', 'NAIVULUNGUTI A', 'NAIVULUNGUTI B', 'NAKASWA', 'SAULO ITALO'],
        'NANSOLOLO': ['BUSANGO', 'BUWOLOGOMA', 'BWOYE', 'KAMANYA', 'NANSOLOLO T/C'],
        'NANTAMALI': ['KAATO', 'KIKOMERA A', 'KIKOMERA B', 'KINANGIRI', 'MBAGO/IBANDA', 'MPITI A', 'MPITI B', 'NANTAMALI TC'],
      },
      'NAWAIKOKE': {
        'BUHANGALA': ['BEEDA', 'BEEDA CENTRAL', 'BUHANGALA T/C', 'BUWANGALA', 'KITAMBOGO A', 'KITAMBOGO B'],
        'BUPENI': ['BUBBULI', 'BUKIMINYI', 'BULANGIRA', 'BULUBA', 'BUPENI', 'KABUTANYA', 'KANAMUNYA', 'LUNYENKE', 'MAHAMBA', 'MENYA', 'YOKOYASI'],
        'KYAMBAYA': ['BUHOYA', 'BUKAABYA', 'MUWUMBA', 'NABITENDE', 'NEKEMIA MUWUMBA', 'YAIRO MAGINO'],
        'NAMAWA': ['BUTATA', 'KAFUNDIKIRE', 'KAFUNDIKIRE T/C', 'KAITANGA', 'KANANSYAIKYE A', 'KANANSYAIKYE B', 'KASOZI', 'NABULO', 'NALUBOMBOKA', 'NALUNYA'],
        'NSAMULE': ['BUKUBAITUBA', 'BUKUNYA', 'BUKYESA', 'BULONDO', 'BUSULETA A', 'BUSULETA B', 'KAMANYA', 'MBADAALI', 'NSAMULE TRADING CENTRE'],
      },
      'NAWAIKOKE TOWN COUNCIL': {
        'BUGWABI WARD': ['BUBINGA', 'BUGWABI A', 'BUGWABI B', 'BUGWABI TC', 'BULANDA', 'BUSINDI', 'MUZINGE'],
        'MUSIHA WARD': ['BUKOSE', 'BUKWAYA', 'BULONDO', 'BUSIHA', 'NAMALEMBA', 'NAMALEMBA CENTRAL', 'NAMALEMBA NORTH', 'NAMALEMBA SOUTH', 'WAMUNSYONO', 'WAMUSYONO A', 'WAMUSYONO B'],
        'MWANGHA WARD': ['BUGYAKU', 'BUJAKU TC', 'BUKUMBI A', 'BUKUMBI B', 'BUSIKWE', 'BUTASA', 'BUTYANGA', 'LYADA', 'SILVE'],
        'NAWAIKOKE WARD': ['BUKUNYA', 'KAJUBU', 'LUKUMI', 'NABUUKU', 'NAWAIKOKE TC'],
        'NOMBE WARD': ['BUKULABONE', 'BUTANDOLA A', 'BUTANDOLA B', 'ISEKESYA', 'WANZALA'],
        'WALYABIRA WARD': ['BUNKULEGA', 'JALAJA', 'KYALIKOBA', 'MAGOMA', 'MULASI', 'MULASI A', 'MULASI B', 'WALYABIRA'],
      },
    },
    'KAMULI': {
      'BALAWOLI': {
        'NABULEZI': ['BUBODHE', 'BUBYASI', 'BUKAAYA', 'BULONDO', 'BUNYANHA', 'BUSIGE', 'BUTANTE', 'BUVUMBI', 'BWASE'],
        'NAMAIRA': ['BUGAYA/BUDIIKUBERA', 'BULUMAGA/BUTEIRA', 'BUNHAMPOGO/BUGANZA', 'BUTOIGO/BULWIIRE', 'BUWALANKAMBA', 'BUWAYA/BUDONGO', 'BUWEMPASA'],
      },
      'BALAWOLI TOWN COUNCIL': {
        'BALAWOLI NORTHERN': ['BALAWOLI T/CENTER', 'BUGAYA', 'BUGOBI', 'BUGOOBE', 'BUGWERI', 'BUKAIBAALE', 'BUKITIMBO', 'BUNANGWE', 'BUSANA', 'BUYIMA', 'BWASE'],
        'KAWAGA SOUTHERN': ['BUDHATEMWA', 'BUGAGA', 'BUGOOBI', 'BUGUWA I', 'BUGUWA II', 'BUSAAMA', 'BUSUUBO', 'BUTALAGE I', 'BUTALAGE II', 'BUTIMBITO', 'BUTOOLI', 'KIRANGIIRA'],
      },
      'BUGULUMBYA': {
        'BUGULUMBYA': ['BUDHULE', 'BUKOSE/BUGOBI', 'BUKWALU', 'BULANGIRA', 'BULAWA', 'BUSOBYA', 'BUSUUBO', 'BUTEKANGA', 'KATANUNI T/CENTRE', 'WAKISIMA'],
        'BUSANDHA': ['BUGOBI', 'BUGUMPE', 'BUKASA', 'BUKULA', 'BUSANDHA T/CENTRE', 'BUTAGULE', 'BUTOMASI', 'BUTYABULE', 'BUWANGA', 'LUKUBAMUTWE'],
        'BUWOYA': ['BUDIIMA', 'BUDUBULI', 'BUFUMBA', 'BULADHA', 'BUSUUWA', 'BUWANDE', 'BUYEMBA'],
        'NAKIBUNGULYA': ['BUBANGA', 'BUGEMA', 'BUKAMWAMI', 'BULONDO', 'BUSOBYA', 'BUSUUBO', 'BUSWAIGIRA', 'BUTABUZA', 'BUTAMBULA', 'BUWAYA', 'BUYIMA', 'BUYOMBA', 'NNUME'],
        'NAWANENDE TOWN BOARD': ['BUGOGOLO', 'BUKOSE', 'BULUSE', 'BUSIWA', 'BUSUBO', 'BUTEFULA', 'MUGULUSI', 'NABIRAMA', 'NANKUNI'],
        'NAWANGOMA': ['BUDUBIRWA', 'BUWAYA', 'BUYIMBIRA', 'ISINWA', 'KIRANGIRA/BUKUBEMBE'],
      },
      'BULOPA': {
        'BUKUTU': ['BUTALE', 'BUTASAGA', 'BUTONTI', 'BUZIDOLO I', 'BUZIDOLO II', 'GABULA', 'NAKYEYA'],
        'BULOPA': ['BUGWALA', 'BUKALIKU', 'BULONDO/BUKAIBALE', 'BULOPA TOWN', 'BUSOBYA', 'BUSUSWA', 'BUYEMBA', 'BUYIMA', 'BUYOBO', 'ITEMBE'],
        'MPAKITONI': ['BUNABI', 'BUTEKANGA', 'BUWONGOLYA', 'BUWOYA', 'KABANDA I', 'KABANDA II', 'MPAKITONYI', 'MUKOKA', 'TASAGA'],
        'NAGAMULI': ['BUGANZA', 'BUGOBI I', 'BUGOBI II', 'BUGWANO', 'BUPIINA/BUKAYA', 'BUTUBA', 'BUWANDE', 'BUYIMA/BWEBYA'],
        'NAGWENYI': ['BUGANZA', 'BUGWANO', 'BUKAIBALE', 'BUNANGWE', 'BUYEGO'],
      },
      'BUTANSI': {
        'BUGEYWA': ['BUGALUKA', 'BUKAYA', 'BUKULUBA', 'BULEEBI', 'BULEETA', 'BULONGO', 'BUSAAMO', 'BUSUULU', 'BUSUUYI', 'BUTATYAMA', 'BUYOGA', 'BWOGA'],
        'BUTANSI': ['BUBOGO', 'BUGAYA II', 'BUGOMBYA', 'BULONDO', 'BULUNGA', 'BULUUKE', 'BUSIIGE', 'BUSUUYI', 'KIWUNGU TRADING CENTRE', 'NTANSI'],
        'NAIBOWA': ['BUBAADHA', 'BUFEESA', 'BUKAAYA', 'BULONDO', 'BULYAMPANDA', 'BUNYOOLA', 'BUSUUYI', 'BUTIMBO', 'BWIGALIRO', 'BWIGULE', 'MUGULUSI'],
        'NALUWOLI': ['ABUTANULA', 'AGALIAWAMU', 'BAKUSEKAMAJA', 'BUTEGERE', 'EZIRA-ALENGERA', 'KANTU', 'KIBUMBAINHEBYO', 'KYEBAJJATOBONA', 'NALUWOLI T/CENTRE', 'NAMAYANDHA', 'TIBASIIMA', 'TIBWAMULALA', 'TUGEZEKU', 'TWABAKOBERANGA', 'TWEYAMBE'],
      },
      'KAGUMBA': {
        'KAGUMBA': ['BUDUUMA', 'BUGAAGA', 'BULAALA', 'BULEMEZI', 'BULINDA', 'DEMBE', 'ISAGAZIIRYA', 'MAWEMBE', 'NAMBAALE'],
        'KASOLWE': ['BUGANZA', 'BUGOOBI I', 'BUGOOBI II', 'BUGULU', 'BULAGALA A', 'BULAGALA B', 'BULASSE', 'BULIMIRA', 'BUSAGIRA', 'BUSUSWA', 'BUTUULA', 'BUYIMA', 'KADHOLWE'],
        'KIBUYE': ['BANDALI', 'BUKALAPYA', 'BUWAISWA', 'BWASE', 'NABITALO A', 'NABITALO B'],
        'KIIGE': ['BUGAGA', 'BUGOBI', 'BUKABETO', 'BUNHIMPI', 'BUNNAMANDA', 'BUSAMO', 'BUSIGE', 'BUSONGOLE', 'BUTYAMA'],
      },
      'KASAMBIRA TOWN COUNCIL': {
        'KASAMBIRA WARD': ['BALUBOINEWA', 'BUBOGO', 'BUDWIGA', 'BUGULUSI', 'BUKANAKU A', 'BUKANAKU B', 'BUKAPERE A', 'BUKAPERE B', 'BUKYONZA A', 'BUKYONZA B', 'BULANDA', 'BUTUUMA', 'KASAMBIRA CENTRAL'],
      },
      'KISOZI': {
        'IZANIRO': ['BUKOOSE', 'BULANGIRA', 'BULONDO/BUBOOKA', 'BUSEETA', 'BUSUUYI', 'BUTADIBA/BUKAAYA II', 'BUYUUKA I', 'BWASE'],
        'KIYUNGA': ['BUBAALE', 'BUDUULI', 'BUGAGA', 'BUKAAYA', 'BUKAAYA I A', 'BUKAAYA I B', 'BUKIIKA', 'BUKOOYO', 'BULAMUKA', 'BULUBANDI', 'BUSANGA', 'BUSIGE/BUDHUGU', 'BUYUUKA II', 'BWANDHO/NAMITEGO', 'KIYUNGA T/C'],
        'NAMAGANDA': ['BUBWEGE', 'BUGWANGA', 'BUKASA', 'BUKYATIFU', 'BULIISO', 'BUZIMBYE'],
      },
      'KISOZI TOWN COUNCIL': {
        'EAST WARD': ['BUBAGO', 'BUDODA', 'BUSIGE', 'IKAABA', 'NAIKESA', 'NAMATOVU'],
        'WEST WARD': ['BUPIINA', 'ISIMBA/NABUKIDI', 'KALEMBE A', 'KALEMBE B', 'KISOZI CENTRE', 'KISOZI EAST', 'KISOZI NORTH', 'KISOZI SOUTH', 'LWANYAMA T.C', 'NABYAMA'],
      },
      'KITAYUNJWA': {
        'BUDHATEMWA': ['BUGONGO/BUBWIIRE', 'BUKAKULA', 'BULANGILA', 'BULONDO/BUGABO', 'BUNANGWE/BUYOBO', 'BUSIBE', 'BUSUUBO/BUGAGA', 'BUYEGO', 'NAMAIRA RURAL'],
        'BUGANZA': ['BUBAMBWE', 'BUDAUDI', 'BUGAGA', 'BULASSE', 'BULIZI', 'BUMWENA', 'BUSUBO/BUYANDA', 'EKIVAEBULAYA'],
        'BUTENDE': ['BUBANDA', 'BUBEEYO', 'BUBYALE', 'BUDONGO', 'BUGULUSI', 'BUKAMIRA', 'BUKUNDHUBA', 'BULERI', 'BULIIRA', 'BULONDO', 'BUNADHOMI', 'BUNAGANHI', 'BUSOOMA', 'NSIIMA'],
        'KITAYUNJWA': ['BUBOIRA/BUBBUPI', 'BUBOKA/BUGOBI', 'BUDIBA', 'BUGAGA/BUGOBE', 'BUGWANTI', 'BUKAFIIKA', 'BUNANDOLO', 'BUNANGWE/BUYUKA', 'BUSIKWE/BULIMIRA', 'BUWAIBALE', 'BWEBYA/BULONDO', 'MPANGA', 'MUGEZI-TALEMWA', 'MWESIGWA', 'NKUUMAMIRIMO'],
        'NAMAGANDA': ['BUDHUGU', 'BUGANZA', 'BUKOSIYA', 'BUKULA', 'BULINDA', 'BUNANGWE', 'BUSUUYI', 'BUTOLI', 'BUWALO', 'BUWATE'],
        'NAMISAMBYA I': ['BUGULERE', 'BUKWANGA/BUKUBEMBE', 'BULAIRE', 'BULEGEYA', 'BUMYUKA', 'BUNAFU', 'BUWAYA/BUYAKOBO', 'BUWENDA', 'BUYONGA', 'BWASE/BUGOBWE', 'MALULU'],
        'NAWANGO': ['BUGAYA', 'BUGOGOLO', 'BUJEMUSI', 'BUKASALA', 'BULAGALA', 'BULONDA', 'BULOYI', 'BUNAKATWE', 'BUNANGWE', 'BUSUTAGAINE', 'BUSUUYI', 'BUTAGAYA', 'BUWAYA', 'BUZIIKO', 'WALUBO'],
        'NAWANSASO': ['BUDHASI', 'BUDOLO/BUDHASI', 'BUGOMBE', 'BUGOMBE/BUSANGA', 'BUSALAMU/BUKASOLO', 'BUSOLE', 'BUWAIBALE', 'BUWAYA/BWAVULA'],
      },
      'MAGOGO': {
        'BUTEME': ['BUBUBULI', 'BUGWALA NORTH', 'BUGWALA SOUTH', 'BUTEME A', 'BUTEME B', 'KAWULE EAST'],
        'KAKIRA': ['BUGOBI EAST', 'BUGOBI WEST', 'BUWANUKA', 'BUYIMA', 'BUYOMBA', 'KAWULE WEST', 'KIRANGIRA'],
        'LWANYAMA': ['KISEEGE', 'LUGADA', 'NKOLONGO'],
        'MAGOGO': ['BUKWALU', 'BUSANGA A', 'BUSANGA B', 'BUSANGA CENTRAL', 'BWASE'],
        'MATUMU': ['BULONDO', 'BUMEGERE', 'BUYAFEESSI', 'BUYOMBA', 'MATUUMU T/C', 'NAKAATO', 'NAMALUMBA', 'NAMULUMBA NORTH', 'NAMULUMBA SOUTH'],
        'NANKANDULO': ['BUBIRO', 'BULANGIRA', 'BULANGIRA EAST', 'BULANGIRA WEST', 'BULUBA', 'BUWAIBI', 'NABUKIDI', 'NANKANDULO T.C'],
      },
      'MBULAMUTI': {
        'BUGONDHA': ['BUGONDHA', 'KASANA', 'KAWERA', 'KIGULUNGUDHI', 'KISWA', 'MUKOKOTOKWA', 'NABAMBA', 'NAWAMPITI'],
        'BULUYA': ['BUGAGA', 'BUGOBI', 'BUGWAIVUBUSIGE', 'BUKOSE', 'BULANGIRA', 'BULONDO', 'BULWASIRA', 'BUTAMWA', 'BUYIMA/BUBOGO', 'BUZALABULWA', 'KIWANHI'],
        'KIYUNGA': ['BUGABALA/BUWAMBIDHI', 'BUKAMBE', 'BUKIIRYE/BUWADAMU', 'BUKOFU/BUKUMBI', 'BUKOSE', 'BUSANO/BULUKAIRE', 'BUSIBE/BUDUTU', 'BUSUYI/BUKAPITI', 'BUWOLOMA', 'BUYEERU/BUSALIRWE', 'NABITAMA/MUTENGU'],
      },
      'MBULAMUTI TOWN COUNCIL': {
        'LUGOLOIRE WARD': ['BUFAKI', 'BUNOGOLA/BUGOLE', 'BUSIIMA', 'BUSUULA', 'BUSUUYI', 'BWEBYA', 'NAKALANGA'],
        'MBULAMUTI WARD': ['BUDHAMULI', 'BUNHENHA', 'BUSOBYA', 'BUWANHANHA A', 'BUWANHANHA B', 'MBULAMUTI TOWN'],
      },
      'NABWIGULU': {
        'NABIRUMBA I': ['BUNAKABOKO', 'BUSANA', 'BWOKO', 'BWOZIIRA'],
        'NABIRUMBA II': ['BUGONDE', 'BUKALU', 'BULUTA', 'BUTWALE'],
        'NABWIGULU': ['BUDUULI', 'BUGAYA', 'BULANDA', 'BULONDO', 'BUNONO', 'BUSIKWE', 'BUSUYI', 'BUWANZU'],
        'NAMUNYINGI': ['BUGAGA I', 'BUGAGA II', 'BUKWANGA', 'BULANGIIRA', 'BULONDO I', 'BULONDO II', 'BUSUSWA', 'NAWAMBALE'],
      },
      'NAMASAGALI': {
        'BWIIZA': ['BUBIRIKI/BUKAWOLE', 'BUFUMBIRO', 'BUGULU/BULIMIRA', 'BUGUMBYA', 'BUKAABI', 'BUKAAYA/BUWERYA', 'BULIMIRA A', 'BUNABIRYO/BULIMIRA', 'BUSUSWA/BULIMIRA', 'BUYEGO/BUNANGWE', 'BUYENGERE', 'KAKINDU', 'KASIIMWE'],
        'KASOZI': ['BUBOOKA', 'BUBUUZA', 'BUGAGA', 'BUGANZA', 'BUGOBI', 'BUGOLE', 'BUKWANGA/BUMBYA', 'BULUNGU', 'BUNANGWE', 'BUSAANO', 'BUSIGE', 'BUYALA', 'MENGO'],
        'KISAIKYE': ['KADUNGU', 'KADUNGU B', 'KAVULE A', 'KAVULE B', 'KAVULE C', 'KAVULE D', 'KAVULE E', 'KAVULE F', 'KISAIKYE A', 'KISAIKYE B', 'KISAIKYE C', 'NANSOLOLO A', 'NANSOLOLO B', 'NANSOLOLO C', 'NANSOLOLO D'],
        'NAMASAGALI': ['KABAGANDA', 'KABANYORO'],
      },
      'NAMWENDWA': {
        'BUGONDHA': ['BUBOGO', 'BUFUUWA', 'BUGOBI', 'BUKWANGA', 'BULUBA', 'BUNAIREKA', 'BUSIKWE', 'BUSUSWA', 'BUTAGA', 'KAYEMBE'],
        'BULANGE': ['BULANGE CENTRAL', 'BUSUUYI', 'BUTAAYA', 'BUWOLOMERA', 'KITIMBO'],
        'BULOGO': ['BUBIGITA', 'BUBIRO', 'BUGABUDIERI', 'BUGAGA MAFUDU', 'BUGAGA-', 'BUGHONGHO', 'BUGWANO', 'BUKAGENYHA', 'BULANGIRA', 'BULONDO', 'BUTUBA', 'BUTYABULE', 'DEMBE'],
        'ISINGO': ['BUGAGA', 'ISINGO B.'],
        'KINU': ['BUBWANA/BUBANDA', 'BUKOOMA/BUNYIRWA', 'BUKOOSE/BUKYALA', 'BUNAMA-BUGWERI', 'BUNANGWE-BUYUUKA', 'BUNYIRWA', 'BUSUUYI-BUBANDA', 'BUSUUYI-BUNYIRWA B'],
        'KYEEYA': ['AGALYAWAMU', 'BUBIRO', 'BUGEMYE', 'BUGOBI', 'BUNABUGO', 'BUSUUBO', 'BUSUYI', 'BUTOGO', 'BUWANGA', 'BWAGUUSA A', 'BWAGUUSA B', 'KATONO'],
        'MAKOKA': ['BUBBUPI', 'BUGUMA', 'BUKAMPALA', 'BUKANTU', 'BUKAPISO', 'BUKENDE', 'BUKYABITA', 'BULONDO', 'BUNIAVU', 'BUTAMIRIKE', 'BUTEGE', 'BUTIMBITO', 'BWASSE', 'LUGUNDHU'],
        'NDALIKE': ['BUDUMBA', 'BUSIRI', 'BUYUBA', 'KAWOLERA', 'KISEEGE', 'NAMBAALE', 'NDALIKE T/C'],
      },
      'NAMWENDWA TOWN COUNCIL': {
        'BULUUYA WARD': ['BUGOBI', 'BULUUYA', 'BUTOGONYHA', 'BUTOOKE-BUSAMBWA'],
        'BULYANGO WARD': ['BULONDO', 'BULYANGO', 'BUSAAKWA', 'BUYOMBA'],
        'BUSEJJA WARD': ['BUGOLE', 'BUKAFUGA A', 'BUKAFUGA B', 'BUSEJJA', 'BUSUUBO', 'BUYINGO'],
        'BUSIMBA WARD': ['BUGOBI', 'BUKWAALU', 'BULUNGU', 'BUSIMBA', 'BUVU', 'NDALI'],
        'MISSION WARD': ['BULONDO', 'BUSOOKO', 'GREEN ZONE', 'INDUSTRIAL', 'MARKET ZONE (TOWN)', 'MISSION'],
      },
      'NAWANYAGO': {
        'BUPADHENGO': ['BUGOBI', 'BUKAAYA', 'BUKULA', 'BUKYONDA', 'BUSABO', 'KAAKO', 'NAKABAALE A', 'NAKABAALE B'],
        'NAWANTUMBI': ['BUGAGA A', 'BUKWANGA', 'BULONDO A', 'BULONDO B', 'BUSEDHE A', 'BUSEDHE B', 'BUSIGE', 'BUWABIRA', 'BUWAGUMA', 'BUYOBO', 'BUYUKA', 'BWASE'],
        'NAWANYAGO': ['BUBIRIZI', 'BUKULUBE', 'BUWANGO', 'IGUMYAMWOYO', 'NALIMAWA'],
      },
      'NAWANYAGO TOWN COUNCIL': {
        'BUPADHENGO URBAN WARD': ['KIROLO', 'KIROLO B'],
        'NAWANTUMBI URBAN WARD': ['BUBAMBWE', 'BUGAGA B'],
        'NAWANYAGO EAST WARD': ['BLOCK A', 'BLOCK B', 'BUDUUDU', 'BUSIMBE', 'BUSUULI A', 'BUSUULI B', 'BUWAIBALE B'],
        'NAWANYAGO WEST WARD': ['BLOCK C', 'BLOCK D', 'BUSIITI', 'BUWAIBALE A'],
      },
      'NORTHERN DIVISION': {
        'BUWANUME WARD': ['BUBBITO', 'BUGULETE', 'BUKAINA', 'BUKATAMBULA', 'BUKYEMBA', 'BULYOKO', 'BUNYOLE', 'BUSANGA', 'BUTEEZE', 'BUYENGERE', 'KYAMULUYA'],
        'KAMULI-SABAWALI WARD': ['BUKWENGE', 'BUNANGWE', 'BUSAKWA/BUTONDA', 'BUYOMBA', 'KIWOLERA'],
        'KASOIGO WARD': ['BUKABALE', 'BUKAPERE', 'BUKOLOBE', 'BUSOIGO', 'BUWENGE MPYA', 'GABULA-KITIMBO', 'WATER SUPPLY'],
        'MUWEBWA WARD': ['ADAMS', 'BUNANGWE', 'BUWEBWA', 'LUFULANDIZI', 'MUTIBWA', 'U.C.B.'],
        'NAMISAMBYA II WARD': ['BUBBALE', 'BUDHUDHU', 'BUGULUMAIRE', 'BUKYERIMBA', 'BULEMA', 'BULONDO', 'BULWAMAZA', 'BUSIGE', 'BUTADIBA', 'BUTERIMIRE', 'BWEEBYA', 'BWIBUKA', 'NAKASEDHERE'],
      },
      'SOUTHERN DIVISION': {
        'BUSOTA WARD': ['ALOWOOZA', 'ASADHAWAIRE', 'BUGONDHA', 'BULAMYA', 'BULANGIRA', 'BUNANGWE', 'BUSOTA', 'BUTAAMA', 'BUTABALA', 'BUTIMBA', 'BWAMBALA', 'BWESE', 'GUTTI', 'KABUKYE T/CENTRE', 'NANVUNANO'],
        'KAMULI-NAMWENDA WARD': ['BUDHUMBULA', 'BUFUMBA', 'BUKAAYE', 'BULINDI', 'BUSANGA', 'BUWALALA', 'BUWUDHA'],
        'MANDWA WARD': ['INDUSTRIAL AREA', 'MUTEKANGA', 'SOROTI'],
        'MULAMBA WARD': ['DENNING', 'MUKASA', 'MULAMBA', 'NABIKAMBA', 'SAZA'],
        'NAKULYAKU WARD': ['BULONGO', 'BUSIBA', 'BUSUBO', 'BUTEKANGA', 'BUYIMBO', 'KANANAGE A', 'KANANAGE B', 'KULINGO'],
      },
      'WANKOLE': {
        'LULYAMBUZI': ['BUDHUBIRWA', 'BUGANDA', 'BUGOBI A', 'BUGOBI B', 'BUKUBEMBE EAST', 'BUKUBEMBE WEST', 'BUNABALA', 'BUSENA', 'BUTIMBWA A', 'BUTIMBWA B', 'LULYAMBUZI CENTRAL', 'LUTEBE A', 'LUTEBE B'],
        'LUZINGA': ['BUBAALE A', 'BUBAALE B', 'BUKITIMBO', 'BULANGIRA EAST', 'BULANGIRA NORTH', 'BULANGIRA SOUTH', 'BULANGIRA WEST', 'BUYIMA', 'GINNERY ZONE', 'KIDHOGWA A', 'KIDHOGWA B', 'LUZINGA CENTRAL', 'NABETA-BULANGIRA', 'NABETA-BULAWA', 'NAGWERE'],
        'WANKOLE': ['BUGOLO EAST', 'BUGOLO WEST', 'BUKASA A', 'BUKASA B', 'BUKITIMBO', 'BUKUTIRA EAST', 'BUKUTIRA WEST', 'BUSIKWE A', 'BUSIKWE B', 'BUTIMBITO I A', 'BUTIMBITO I B', 'BUTIMBITO II A', 'BUTIMBITO II B', 'BUWUMBWE', 'BUYERU A', 'BUYERU B', 'NAWANDYO CENTRAL'],
      },
    },
    'LUUKA': {
      'BUKANGA': {
        'BUDONDO': ['BUDONDO A', 'BUDONDO B', 'BUGOBA', 'KIMANTO A', 'KIMANTO B'],
        'BUWOLOGOMA': ['BUGOGO', 'BUKAADE', 'BUKWANGA', 'BUWOLOGOMA CENTRAL', 'KATALAKABI', 'NABINONI', 'NAKAMINI', 'NDHOYA A', 'NDHOYA B'],
        'KIROBA': ['BIGUNHO', 'BULONDE', 'BUSANDHA', 'KIROBA-BUDOMA', 'KISIMBA', 'NAWANTALE'],
        'NABUBYA': ['BUDOMA A', 'BUDOMA B', 'BUDOMA C', 'BUNHIRIRA', 'NABUBYA A', 'NABUBYA B', 'NAKABONDO'],
        'NAMUKUBEMBE': ['BUKANGA-BUKENDI', 'BULWASIRA', 'BUMANHA A', 'BUMANHA B', 'BUMANHA CENTRAL', 'KANTENGA', 'NAMUKUBEMBE A', 'NAMUKUBEMBE B'],
      },
      'BUKOOMA': {
        'BUKOOMA': ['BUKOOMA A', 'BUKOOMA B', 'MISITA'],
        'BUKYANGWA': ['BUDHANA A', 'BUDHANA B', 'BUKYANGWA A', 'BUKYANGWA B'],
        'NAIGOBYA': ['NAIGOBYA A', 'NAIGOBYA B', 'NAIGOBYA T/C', 'NAIRIKA EAST', 'NAIRIKA WEST'],
        'NAMANSENDA': ['BULALU', 'BUSAKU', 'KIRIMWA A', 'KIRIMWA B', 'NABIMOGO A', 'NABIMOGO B', 'NAMANSENDA A', 'NAMANSENDA B'],
        'NAMULANDA': ['GWEMBUZI A', 'GWEMBUZI B', 'NAMULANDA A', 'NAMULANDA B'],
      },
      'BUKOOVA TOWN COUNCIL': {
        'BUKANHA WARD': ['BUMYUKA', 'BUYEGO', 'IBANDA YONNA', 'ISAKA BUGA', 'LUGANDA'],
        'BUKOOVA CENTRAL WARD': ['AGAPE ZONE', 'CENTRAL ZONE', 'KISAMBIRA ZONE', 'KUNYA ZONE', 'YONNA ZONE'],
        'BUKOOVA RURAL WARD': ['BUFUMBA ZONE', 'BUGUMBA ZONE', 'KILANGILA ZONE', 'KITESO ZONE'],
        'BUNABALA WARD': ['BUGAYA ZONE', 'BUKOOVA P/S ZONE', 'BUSUSWA ZONE', 'BUSUUYI ZONE', 'BUYINGO ZONE'],
        'BUSANDA WARD': ['BUDOOLA ZONE', 'BWINIKE ZONE', 'CENTRAL ZONE', 'LANDI ZONE', 'NGALAMBI ZONE'],
        'BUTASERWA WARD': ['BUFUMBA ZONE', 'BUGAGA ZONE', 'BULANGIRA ZONE', 'CENTRAL ZONE'],
        'BUYOGA WARD': ['BUFUMBA ZONE', 'BUKYEGA ZONE', 'BUSUUBO ZONE', 'BUYINGO ZONE', 'TESO ZONE'],
        'MAKUUTU WARD': ['BUBIRO ZONE', 'BUDHUGU ZONE', 'BUYINGO ZONE', 'BWANDA ZONE'],
        'NABYOTO WARD': ['BUKAMA ZONE', 'CENTRAL ZONE', 'KISITA ZONE', 'MUTYAGOMA ZONE', 'RAILWAY ZONE', 'WAKASA ZONE'],
        'NAWANSEGA WARD': ['BUKUBEMBE/BUGURU ZONE', 'BUKWANGA ZONE', 'BULONDO ZONE', 'BUYAWUKA ZONE', 'CENTRAL ZONE', 'KISEEGE ZONE', 'LANDI ZONE'],
      },
      'BULANGA TOWN COUNCIL': {
        'BULANGA WARD': ['BULANGA ESTATE', 'KASOKOSO', 'KATAIKE', 'KIWUMBI'],
        'ITWE WARD': ['BUGWANALA A', 'BUGWANALA B', 'ITWE', 'TAGOOLE'],
        'MAWUNDO WARD': ['BUDHEBERA', 'KYANKUZI', 'MUFUWA', 'NABUKALU'],
        'NANTAMU WARD': ['ABALAWUWE', 'LUMBUYE', 'LUSWIGA', 'NANTAMU'],
        'WALIBO WARD': ['KISANSA', 'LUWANGULA', 'WALIBO', 'WALIBO LULENZI'],
      },
      'BULONGO': {
        'BUDHABANGULA': ['BUDHABANGULA A', 'BUDHABANGULA B', 'KIBUUTU'],
        'BUGONYOKA': ['BUGONYOKA A', 'BUGONYOKA B', 'BUZAAYA', 'NAKISENYI A', 'NAKISENYI B'],
        'BUKENDI': ['BUGABULA A', 'BUGABULA B', 'BUKENDI', 'NABITAAMA A', 'NABITAAMA B'],
        'BULONGO': ['BUWAISWA', 'KAMWIRUNGU A', 'KAMWIRUNGU B'],
        'NAKABUGU': ['BUSEETE', 'BUYUNZE A', 'BUYUNZE B', 'NAKABUGU A', 'NAKABUGU B'],
        'NAMALEMBA': ['BULIKE', 'BUSALA', 'KASOZI', 'NAMALEMBA'],
      },
      'BUSALAMU TOWN COUNCIL': {
        'BUSALAMU EAST WARD': ['BOTONDOLO B', 'BUSALAMU CENTRAL', 'BUTONDOLO A', 'KIDYOPE'],
        'BUSALAMU NORTH WARD': ['BUSIRINGE A', 'BUSIRINGE B', 'KIRINGO A', 'KIRINGO B'],
        'BUSALAMU SOUTH WARD': ['KIGULAMO A', 'KIGULAMO B', 'LUKUNHU A', 'LUKUNHU B'],
        'BUSALAMU WEST WARD': ['LUKOTAIME A', 'LUKOTAIME B', 'LUKOTAIME C', 'LUKOTAIME D'],
      },
      'IKUMBYA': {
        'BUNAFU': ['BUNAFU A', 'BUNAFU B', 'NABISIRA', 'NAWANYAGO'],
        'IKUMBYA': ['BUWUTU', 'IKUMBYA', 'NSAMBYA', 'WANDAGO'],
        'INUULA': ['BUDHUUBA A', 'BUDHUUBA B', 'BUGAMBO', 'INUULA'],
        'NAWAKA': ['BUGONZA', 'KAWANGA', 'NANTAMALI', 'NAWAKA A', 'NAWAKA B', 'NAWAKA CENTRAL'],
        'NTAYIGIRWA': ['BUKOBBO', 'BULIKE', 'IDOOME EAST', 'IDOOME WEST', 'NABITENDE', 'NTAYIGIRWA'],
      },
      'IRONGO': {
        'IRONGO': ['BUFUMBA', 'BUWALA', 'GANSEMBYE', 'IGANGA A', 'IGANGA B', 'IRONGO', 'NAIMULI A', 'NAIMULI B', 'NSIRIRA'],
        'KALYOWA': ['BUKYAMATA', 'KALYOWA A', 'KALYOWA B', 'KIGUNGA'],
        'KIBINGA': ['KANTENGA', 'KIBINGA A', 'KIBINGA B', 'NAKAVUMA', 'NKANDAKULYOWA'],
        'KYANVUMA': ['BUWAIGALA', 'KAZIGO', 'KIWALAZI', 'NAKABAALE B', 'NAKASEDHERE'],
        'NAWANYAGO': ['BUBIRO', 'BUGAGA A', 'BUGAGA B', 'BUGOBI', 'BUTOGONYA', 'BUYEMBA', 'LUZINGA PARK', 'NAWAMPITI'],
      },
      'KYANVUMA TOWN COUNCIL': {
        'BUNIKO WARD': ['BUNIKO A', 'BUNIKO B', 'MAWALE', 'MBOGA'],
        'MAGADA WARD': ['KASOKOSO', 'KIBUYE LC1', 'OLD MARKET'],
        'NAKABAALE WARD': ['BONDO', 'NAKABAALE A', 'NAKABAALE SCHEME'],
        'NAKABAMBWE WARD': ['KIGAITO', 'KYANVUMA', 'NABIKAMBA', 'NAKABAMBWE'],
        'NSIMAKATONO WARD': ['BUDUGU', 'BULINDA', 'MPALA', 'NSIIMA TRADING CENTRE'],
      },
      'LUUKA TOWN COUNCIL': {
        'BUSIMAWU WARD': ['BUDHUMBWIRE', 'BUSIMAWU', 'WAIGUGWE'],
        'BUSONGA WARD': ['BUKABOLI', 'BUSONGA'],
        'KITWEKYAMBOGO WARD': ['MBOGO', 'NAWAMWENA', 'NAWANSUDE'],
        'KIYUNGA WARD': ['KIYUNGA CENTRAL', 'KIYUNGA HOSPITAL', 'KIYUNGA INDUSTRIAL'],
        'LWADA WARD': ['BUWAMBUZI', 'LWANDA', 'NTANDAGWE'],
      },
      'NAWAMPITI': {
        'BUGOMBA': ['BUGOMBA', 'BUWANDA', 'NAWANDYO'],
        'BUYOOLA': ['BUYOOLA', 'IKONIA A', 'IKONIA BUSIGE', 'IKONIA CENTRAL', 'NAKYERE'],
        'NAKISWIGA': ['BUWAMWA', 'NABIKUYI', 'NAKISWIGA A', 'NAKISWIGA B', 'NAMAGERA', 'NJABABONA'],
        'NAWAMPITI': ['BUZIMBA', 'KITUUTO A', 'KITUUTO B', 'NAWAMPITI-BUKYANGWA'],
        'NAWANKOMPE': ['KASOZI', 'NAWANKOMPE A', 'NAWANKOMPE B', 'WALUGABA'],
      },
      'WAIBUGA': {
        'BUSIIRO': ['BULINDI', 'BUSIIRO', 'BUSIIRO T/C', 'BWAMBA', 'KYAMAWUNDO', 'NANVUNANO \'A\'', 'NANVUNANO \'B\'', 'NANVUNANO \'C\''],
        'BUTIMBWA': ['BUKYOGO', 'BUTIMBWA A', 'BUTIMBWA B', 'IKONKO', 'LWANIKA', 'NAMAKAKALE A', 'NAMAKAKALE B', 'WAIBUGA A', 'WAIBUGA B'],
        'ITAKAIBOLU': ['BUKAPALA', 'BUWIIRI', 'ITAKAIBOLU A', 'ITAKAIBOLU B', 'KIGAYA'],
        'LWAKI': ['KIWANYI', 'LWAKI', 'MAUMO', 'NAMADOPE'],
      },
    },
    'MAYUGE': {
      'BAITAMBOGWE': {
        'BUGODI': ['BUGODI A', 'BUGODI B', 'MUSITA B', 'NAWANGIRI'],
        'BUTTE': ['BUTE \'A\'', 'BUTE \'B\'', 'NALWESAMBULA'],
        'IGEYERO': ['IGEYERO A', 'IGEYERO B', 'MUKUTA', 'WAGONA'],
        'KATONTE': ['BUWANGA \'A\'', 'BUWANGA \'B\'', 'KATONTE', 'NAMAGERA'],
        'LUGOLOLE': ['BAITAMBOGWE', 'LUGOLOLE B', 'LUGULOLE A', 'MBIRIZI'],
        'LUKONE': ['LUKONE', 'MAGAMAGA', 'NSINDA'],
        'MULINGILIRE': ['BUBAMBWE', 'IZINGA', 'MULINGIRIRE', 'MUSITA A', 'NAMUSENWA'],
        'WAINHA': ['NABALONGO A', 'NABALONGO B', 'WAINHA \'A\'', 'WAINHA \'B\''],
      },
      'BUGADDE TOWN COUNCIL': {
        'BUGADE WARD': ['BUGADDE A', 'BUGADDE B', 'BUGADDE C', 'BUGADDE EAST', 'BUGADDE NORTH', 'BUGADDE WEST', 'BUGOYA'],
        'BUSENDA WARD': ['BUSENDA A', 'BUSENDA B', 'BUSENDA C'],
        'KITYERERA WARD': ['KITYERERA A', 'KITYERERA B', 'KITYERERA C'],
        'NAKIBENGO WARD': ['ITUBA A', 'ITUBA B', 'KIKOKOLI', 'NAKIBENGO'],
      },
      'BUKABOOLI': {
        'BUGOTO': ['BUGOTO A', 'BUGOTO B', 'BUTUMBULA', 'KAKOGE', 'KITUMBEZI', 'LULANDA', 'MUNYAZI', 'MUSUBI', 'NAMULULI', 'NAWAMPONGO'],
        'BUGUMIA': ['BUDUMBA', 'KALIRO', 'KANYANA', 'KIRONGO A', 'KIRONGO B', 'MAKOOMA', 'NAKASUWA'],
        'BUKABOOLI': ['BUKABOOLI', 'KALAGALA A', 'KALAGALA B', 'KIKUNYU', 'NAMULWANA \'A\'', 'NAMULWANA \'B\''],
        'BUYUGU': ['BUSITEMA', 'BUYUGU', 'IGAYAZA', 'KINAWAMBUZI', 'MBALE', 'NABYAMA', 'NABYAMA BEACH', 'NAMAKOKO'],
        'MATOVU': ['BUKANGA', 'MATOVU', 'NABIWERO', 'NAKIBAGO'],
        'MAYIRINYA': ['BUSIRA', 'KASOZI', 'KASOZI B', 'LUWUTA', 'LWANDERA', 'MAIRINYA \'B\'', 'MAIRINYA A', 'NAWANDEGEYI'],
      },
      'BUKATUBE': {
        'BUKALEBA': ['BUKALEBA', 'NAKALANGA A', 'NAKALANGA B', 'NAMUGONGO', 'WALUMBE BEACH'],
        'BUYEMBA': ['BUBALAGALA', 'BUKASERO A', 'BUKASERO B', 'BUYEMBA \'A\'', 'BUYEMBA \'B\'', 'LUUBU A', 'LUUBU B', 'MUGERI A', 'MUGERI B'],
        'LWANIKA': ['BUDHALA \'A\'', 'BUDHALA \'B\'', 'BUKATUBE \'A\'', 'BUKATUBE B', 'BUTIMBWA', 'BUWOLOMERA', 'KAPALUKO', 'LUKINDU A', 'LUKINDU B', 'LWANIKA A', 'LWANIKA B', 'NDHOKERO A', 'NDHOKERO B', 'WAMONDO'],
        'MAUTA': ['BUGULUMA', 'BUYOKA', 'KABUKI', 'KYANDO', 'MAUTA'],
        'MBIRABIRA': ['BUFUTA A', 'BUFUTA B', 'BUGWANANDALA', 'BUWERERE', 'MASAKA', 'MBIRABIRA'],
      },
      'BUSAKIRA': {
        'BUKUNJA': ['BUKUNJA \'A\'', 'BUKUNJA \'B\'', 'BUSAALA', 'LUBALI', 'NAMISU \'A\'', 'NAMISU \'B\'', 'NAMISU C'],
        'BUTANGALA': ['BUBALI', 'BUGOYE', 'BUTANGALA \'A\'', 'BUTANGALA \'B\'', 'MUKONDA', 'NAMIRO', 'WAITA'],
        'KALUUBA': ['BUSAKIRA \'A\'', 'BUSAKIRA \'C\'', 'BUSAKIRA \'D\'', 'BUSAKIRA B', 'KAFUMITA', 'KALUUBA \'A\'', 'KALUUBA \'B\'', 'KALUUBA \'C\''],
        'MAUMU': ['BUSEERA B', 'BUYANIRWA', 'MAUMU A', 'MAUMU B', 'NAMWOBA'],
        'WAMBETE': ['BUSEERA \'A\'', 'BUSEERA \'C\'', 'MACHECHE', 'WAMBETE \'A\'', 'WAMBETE \'B\''],
      },
      'BUWAAYA': {
        'BUWAISWA': ['BUBAGO', 'BUWAAYA', 'BUWAISWA', 'NABUYAGI', 'NTAFUNGIRWA'],
        'BUWOLYA': ['BUWOLYA', 'IVUGUNYU', 'IWUUBA', 'KAKINDU', 'NTINDA'],
        'ISIKIRO': ['BUKOOBA', 'IBANGA', 'ISIKIRO', 'KANYABWINA', 'KIKUBO'],
        'KABAINGIRE': ['KABAINGIRE', 'NAKATE', 'NAMADHI', 'NAMATALE', 'NAWANVUBU'],
        'NSANGO': ['BULONDO', 'LUGANGU', 'NABITTU', 'NAMAGO', 'NSANGO'],
      },
      'BWONDHA TOWN COUNCIL': {
        'BWONDHA CENTRAL WARD': ['BWONDHA B', 'BWONDHA CENTRAL', 'BWONDHA D'],
        'BWONDHA SOUTH WARD': ['BWONDHA A', 'BWONDHA EAST', 'NABIDONGA'],
        'MAKONKO WARD': ['KAYANJA', 'KIYONJO', 'MAKONKO A', 'MAKONKO B', 'MIREMBE'],
        'MUSOMA WARD': ['BUKIMERA', 'MUSOMA', 'NAKAWA'],
        'NALUBABWE WARD': ['BWONDHA C', 'MULOWOZA', 'NALUBABWE A', 'NALUBABWE B'],
        'NKALANGA WARD': ['BWONDHA CENTRAL MARKET', 'NKALANGA A', 'NKALANGA B', 'VICTORIA'],
      },
      'IMANYIRO': {
        'BUFULUBI': ['BUFULUBI A', 'BUFULUBI B', 'BUKOMYA', 'BUVUNA', 'KISULE', 'LWABALA', 'NAKIWATA'],
        'MAGADA': ['BULYAMPINDI', 'LUYIRA', 'MAGADA', 'NAMADUDU', 'NAMAKAKALE', 'WALUGOGO', 'WANTE'],
        'MAYUGE': ['BUDHEBERA', 'BUKAWONGO', 'BWIWULA', 'LUWANULA', 'MATUBA'],
        'MBAALE': ['IGUNDA', 'IMANYIRO', 'KAKUNU', 'MAGUNGA', 'MBAALE', 'NAMWOGI', 'WANSWA'],
        'NKOMBE': ['KITOVU', 'KYANDAILE', 'LWANDA', 'NAKABALE', 'NKOMBE \'A\'', 'NKOMBE \'B\''],
      },
      'JAGUZI': {
        'BUMBA': ['BUKABAMBWE', 'BUYAKO BEACH', 'BUYAKO VILLAGE', 'GALILAYA'],
        'JAGUZI': ['BUSABALA A', 'BUSABALA B', 'BWAYA/BUKEMBO', 'GOOLI A', 'GOOLI B', 'KAZIRU', 'MUBEMBE', 'MUSOMA', 'NABUKALU A', 'NABUKALU B'],
        'KAAZA': ['KAAZA A', 'KAAZA B', 'SIMWE ISLAND'],
        'MASOLYA': ['MASOLYA \'A\'', 'MASOLYA \'B\'', 'MASOLYA CENTRAL'],
        'SAGITU': ['BUSWETA', 'DEMBE', 'MAGANDA', 'NALUWERERE'],
        'SERINYABI': ['KOLOLO', 'LUKOBA', 'MASAMBA'],
      },
      'KIGANDALO': {
        'BUGONDO': ['BUGONDO', 'NABUKONE', 'NAKAWA', 'NAMALEGE', 'WALUKOKO'],
        'ISENDA': ['BUGUNDA', 'ISENDA', 'ISENDA A', 'KATALAKABI', 'NAMAIGA', 'NAMATOVU', 'NANVUNANO', 'NVUNWA', 'WALULENGA'],
        'KIGANDALO': ['KIGANDALO A', 'KIGANDALO B', 'NAIJERIA', 'NAKASERO', 'NAKAZIGO', 'NAKIDUBULI', 'NAMPU', 'NDALAEGOBYE', 'WANDAWA'],
        'KIGULU': ['BUBBALYA', 'BUYAGA', 'KIGULU', 'KIREWE', 'NAMASAKA', 'NAMUGOLO', 'NSUMBA'],
        'KIOGA (MAYENGO)': ['BUSUI', 'BUYEGO', 'BWEZA', 'KAZINGA', 'KIOGA', 'LUKUNYU', 'NABIKOMO', 'NAKAVULE', 'SESE'],
        'MALEKA': ['ISOOLA', 'KIGULAMU', 'MABIRIZI', 'MALEKA A', 'MALEKA B', 'NAKITWALO', 'WANKONGE'],
      },
      'KITYERERA': {
        'BUBINGE': ['BUBINGE', 'BULIDHA', 'BUSIMO', 'IGUNDA', 'KIKANDWA'],
        'BUKALENZI': ['BUKALENZI', 'BUKOBA \'B\'', 'BUKOBA A', 'BUKOBA CENTRAL', 'BUKUKU', 'LUTALE \'A\'', 'LUTALE D', 'MASHAGA A', 'MASHAGA B', 'NAMALERE', 'NGAYAMA'],
        'KITOVU': ['KABAGANJA', 'KIKOMA', 'KITOVU', 'LUTALE \'B\'', 'LUTALE C', 'MITIMITO', 'NTAMBI'],
        'NDAIGA': ['BUBALULE A', 'BUBALULE B', 'NAKIRIMIRA A', 'NAKIRIMIRA B', 'NAKIRIMIRA C', 'NDAIGA A', 'NDAIGA B', 'NDAIGA C'],
        'WANDEGEYA': ['KATUBA', 'NENDA A', 'NENDA B', 'WAKIWUNGU', 'WANDEGEYA A', 'WANDEGEYA B'],
      },
      'MAGAMAGA TOWN COUNCIL': {
        'BUKOLI WARD': ['BUKOLI A', 'BUKOLI B', 'BUKOLI C', 'MUTUKULA'],
        'MAGAMAGA WARD': ['KAWUDHU', 'MAGAMAGA T/C', 'MARKET ZONE', 'TASAGA'],
        'WABULUNGU WARD': ['BODA', 'BRIDGE', 'DONGA', 'MUYENGA', 'NAKASERO', 'NAMUFUMA', 'WABULUNGU A'],
        'WANDAGO WARD': ['CHURCH OF UGANDA', 'ISIIKO', 'WANDAGO A', 'WANDAGO B'],
      },
      'MALONGO': {
        'BUKATABIRA': ['BUKATABIRA A', 'BUKATABIRA B', 'BULUBUDHE', 'NKOLONGO', 'NKOLONGO A', 'NKOLONGO B', 'NKOLONGO C'],
        'BULUTA': ['BUKAGABO \'A\' BEACH', 'BUKAGABO \'A\' VILLAGE', 'BUKAGABO \'B\' BEACH', 'BUKAGABO \'B\' VILLAGE', 'BUKAGABO C', 'BULUTA A', 'BULUTA B', 'BULUTA BULAIRE', 'BULUTA C', 'BULUTA IKOLE', 'BULUTA KITOGO', 'MALINDI'],
        'BUMWENA': ['BUGATA', 'BUGOOMA BEACH', 'BULEBI', 'BUMWENA A', 'BUMWENA B', 'NAKIGO A', 'NAKIGO B', 'NAMASONKO', 'NAWAMPONGO'],
        'MALONGO': ['KABUKA', 'KABUKA BEACH', 'KAYANJA BEACH', 'KAYANJA VILLAGE', 'MALONGO A T/C', 'MALONGO B', 'MALONGO B T/C', 'MALONGO C', 'MALONGO CENTRAL', 'MALONGO D', 'MALONGO EAST', 'MALONGO INN', 'MALONGO NORTH', 'MALONGO UPPER', 'MALONGO WEST', 'MASAKA', 'NANGO BEACH', 'NANGO VILLAGE'],
        'NAMADHI': ['NAMADHI A', 'NAMADHI B', 'NAMADHI BEACH', 'NAMADHI C', 'NAMADHI D', 'NAMADHI SOUTH', 'NAMADHI T/C', 'NAMAVUNDHU KYONDO', 'NAMAVUNDHU T/C'],
        'NAMONI': ['BULUNGU', 'MAGOOLA A', 'MAGOOLA B', 'NAMONI \'A\'', 'NAMONI \'B\'', 'NAMONI BEACH', 'WAMALA'],
      },
      'MAYUGE TOWN COUNCIL': {
        'IKULWE WARD': ['BUGINGO', 'IGAMBA A', 'IGAMBA B', 'KATWE', 'TSE-TSE'],
        'KASUGU WARD': ['DWALIRO', 'KASUGU \'A\'', 'KASUGU \'B\''],
        'KAVULE WARD': ['BUDHEBERA', 'DFI', 'KAVULE', 'MAYUGE CENTRAL'],
        'KYEBANDO WARD': ['KYEBANDO', 'NAKABAFU', 'ST. MULUMBA', 'WAKALENDE'],
      },
      'MPUNGWE': {
        'BUYERE': ['BUGUWA', 'BUYERE', 'MUSIMA', 'MUSITA', 'NAKITAMU'],
        'MAINA': ['BUSU', 'KABERE', 'KYETE', 'MAINA', 'MWEZI'],
        'MUGGI': ['BUWANUKA', 'KASOKWE', 'MPUNGWE', 'MUGGI'],
        'WAIRAMA': ['BULYANGADA', 'BUWALIRA', 'KASUTAIME', 'MAUMA', 'MPUMU', 'MUNYONYI', 'NAWANKOLE', 'WAIRAMA'],
        'WAMULONGO': ['BUSWIKIRA', 'MAKOOVA', 'NAMATOOKE', 'WAMULONGO', 'WANDAWA'],
      },
      'WAIRASA': {
        'BUSUYI': ['BUGABWE', 'BUSOWANIRE', 'BUSUYI', 'BUYEMBA', 'KASITA'],
        'IGULUIBI': ['IGULUIBI A', 'IGULUIBI B', 'NTOKOLO', 'WAIBALE'],
        'MISOLI': ['BUSALAMU', 'MISOLI BEACH', 'MISOLI TRADING CENTRE', 'MISOLI VILLAGE', 'NTINKALU T/C'],
        'WANDAGO': ['LUGWARA QTRS', 'NAMALERE', 'WAIRASA TRADING CENTRE'],
      },
    },
    'NAMAYINGO': {
      'BANDA': {
        'BUCHUMBA': ['BUCHUMBA', 'BULUNDIRA', 'BUNINI', 'BUSINOHO', 'BUSUMA', 'MUNYOLONDA', 'NAMAKE', 'OKONGA'],
        'BUJWANGA': ['BUBANGI', 'BUDUNGA EAST', 'BUDUNGA WEST', 'BUJWANGA EAST', 'BUJWANGA WEST', 'BUSIRO', 'BUSIRO BEACH', 'HALABA', 'MABENDE', 'NABWEYO', 'NAKUDI', 'NAMBANO', 'SEKA'],
        'LUGALA': ['BUDALA', 'BUHIMA', 'BUYUNDO', 'LUGALA BEACH', 'MATALE', 'MAYANJA', 'SIDENDE', 'SISIRO'],
      },
      'BANDA TOWN COUNCIL': {
        'BUKEDA WARD': ['BUHULA', 'BUKEDA', 'BUTEMO', 'SIABONA'],
        'BUWOYA WARD': ['BUNYALAWO', 'BUSEKESE', 'BUSUDIA', 'BUWOYA', 'MUHUBU'],
        'BUYOMBO WARD': ['BUDIANGA', 'BUYOMBO', 'NANJALA', 'SIAHOOLI', 'SIAMBA'],
        'LUTOLO WARD': ['LUNAYE', 'LUTOLO', 'SIROWA'],
        'MAGOOLI WARD': ['BAALE', 'BWOGOMI', 'MAGOOLI', 'NAMABONI'],
        'NANGERA WARD': ['BUCHUNIA', 'GAMBABWAMI', 'NANGERA'],
      },
      'BUHEMBA': {
        'BUHEMBA': ['BUHEMBA', 'BULUNDIRA EAST', 'BULUNDIRA WEST', 'LWANIHA', 'MUHUWA', 'SITYOHE'],
        'BUKEWA': ['BUKEWA CENTRAL', 'BUKEWA EAST', 'BUKEWA WEST', 'MARUBA', 'MUGANIRO EAST', 'MUGANIRO WEST', 'ONGOJJE EAST', 'ONGOJJE WEST'],
        'BUWONGO': ['BUKIMBI \'A\'', 'BUKIMBI B', 'BUKIMBI C', 'BUWONGO CENTRAL', 'BUWONGO EAST', 'BUWONGO WEST', 'MATIKO EAST', 'MATIKO WEST'],
        'DOHWE': ['DOHWE CENTRAL', 'DOHWE EAST', 'DOHWE WEST', 'LUWERERE \'A\'', 'LUWERERE \'B\'', 'NABWERE NORTH', 'NABWERE SOUTH', 'NAMUWONGO'],
        'SINDE': ['GENGULUHO', 'MAKADA', 'NAMALERE', 'NAMAYOMBE', 'SINDE'],
      },
      'BUKANA': {
        'BIISA': ['BIISA', 'YEBE'],
        'BUDUMA': ['BUDUMA', 'BUHERE', 'BUHOBI', 'BUHONE', 'BUKANI', 'BUKUBUNGU', 'HABAGAYA', 'MUGABE', 'NAMAVUNDU'],
        'BUGANA': ['BUBWIBO', 'BUGANA', 'BULIANI', 'LWORE', 'MABUKA', 'NDAYIGA', 'SOMOHO'],
      },
      'BUSWALE': {
        'BUBANGO': ['BUBANGO', 'NALWIGI', 'NAMAHUHUNI', 'NANJOFU \'A\'', 'NANJOFU \'B\''],
        'BUNGECHA': ['BUDANGI', 'BUDIBA', 'BUGENCHA', 'BUHATANDU', 'BUKECHI A', 'BUKECHI B'],
        'BUSWALE': ['BUGALAMA', 'BUHUNYA A', 'BUHUNYA B', 'BULIYO A', 'BULIYO B', 'BUNYIHERI', 'NASISA A', 'NASISA B', 'SIDOME', 'SIMIGINI'],
        'MADOWA': ['BUSANKA A', 'BUSANKA B', 'LUVUNYA A', 'LUVUNYA B', 'MADOWA \'A\'', 'MADOWA \'B\'', 'NALUBABWE', 'UMBWE'],
        'NAMAYUGE': ['BUHIMA', 'HABALA', 'HASEBERE', 'LUGUNJA', 'NAMAJI A', 'NAMAJI B', 'NAMAYUGE', 'TETE'],
        'NANSUMA': ['BUHWANJA', 'BUMOLI A', 'BUMOLI B', 'MAKAALO', 'MASODI A', 'MASODI B', 'NANSUMA A', 'NANSUMA B', 'SIJAGAJO A', 'SIJAGAJO B'],
      },
      'BUYINJA': {
        'GONDOHERA': ['BUDIMO', 'BUTAJJA', 'GONDOHERA', 'NAMUHOLOHOHO'],
        'KIFUYO': ['KIFUYO \'A\'', 'KIFUYO \'B\'', 'LUGULE', 'MUSOOKA', 'NSANGO \'A\'', 'NSANGO \'B\''],
        'LWANGOSIA': ['BUBWOYI', 'BUGAYA', 'BULOHA EAST', 'BULOHA WEST', 'LWANGOSIA EAST', 'LWANGOSIA WEST', 'NAMUTABA EAST', 'NAMUTABA WEST', 'SIBONDWE'],
        'NSONO': ['BUGOMA \'A\'', 'BUGOMA \'B\'', 'BUZIGE', 'NABYANGA', 'NAKASOLO', 'NAMAVUNDU NORTH', 'NAMAVUNDU SOUTH', 'NSONO EAST', 'NSONO WEST'],
        'SYANYONJA': ['BUBOKO', 'HOHOMA', 'MAGETA', 'SYANJONJA \'C\'', 'SYANYONJA \'A\'', 'SYANYONJA \'B\''],
      },
      'LOLWE': {
        'HAMA': ['MAKINDYE', 'SIAMULALA', 'SIRO', 'WAYASI'],
        'LOLWE EAST': ['BUKANGAWA', 'BUTANIRA', 'MWAGODA', 'MWANGO', 'RABOLO', 'SINGILA CENTRAL', 'SINGILA WEST'],
        'LOLWE WEST': ['BUYANDO GATUNDU', 'GOROFA EAST', 'GOROFA WEST', 'HAKARI', 'KAMWANGA', 'KANDEGE', 'NYALO'],
      },
      'MUTUMBA': {
        'BUCHIMO': ['BUCHIMO A', 'BUCHIMO B', 'BUCHIMO C', 'BUMERU A', 'BUMERU B', 'BUMERU C'],
        'LUBANGO': ['LUBANGO \'A\'', 'LUBANGO \'B\'', 'LUGAGA', 'MULWANDHA \'A\'', 'MULWANDHA \'B\'', 'MUSOMA'],
        'MWEMA': ['BULUNDIRA A', 'BULUNDIRA B', 'BUTEBEYI \'A\'', 'BUTEBEYI \'B\'', 'BUTEBEYI \'C\'', 'MULOMBI A', 'MULOMBI B', 'MULOMBI C', 'SITYOHE'],
      },
      'MUTUMBA TOWN COUNCIL': {
        'BULULE WARD': ['BULULE CENTRAL', 'NAMAGANDA \'A\'', 'NAMAGANDA \'B\'', 'NAMAGENGE'],
        'HATUMBA BANJA WARD': ['BUMECHI', 'NAHAIGA', 'NAMAVUNDU'],
        'LUBIRA WARD': ['BUGALI \'A\'', 'BUGALI \'B\'', 'LUBIRA', 'NATIHALU'],
        'MAWA WARD': ['BUSIULA', 'LUFUDU', 'MAAWA', 'SIMASE'],
        'MUTUMBA NORTH WARD': ['BUDIBA', 'HAGULU', 'MUTUMBA \'B\'', 'NATOHOLO'],
        'MUTUMBA SOUTH WARD': ['MUTUMBA \'A\'', 'MUTUMBA CENTRAL', 'SIDOME A', 'SIDOME B'],
      },
      'NAMAYINGO TOWN COUNCIL': {
        'BUDIDI WARD': ['BUDIDI', 'BULETU', 'BUYIITI', 'GABA', 'NAMASULO A', 'NAMASULO B'],
        'BULAMBA WARD': ['BUKOVA', 'BULAMBA \'A\'', 'BULAMBA \'B\'', 'MPANO \'A\'', 'MPANO \'B\'', 'NAWAYIBETE'],
        'NAMAYINGO CENTRAL WARD': ['NAMAYINGO CENTRAL', 'NAMAYINGO EAST', 'NAMAYINGO NORTH', 'NAMAYINGO SOUTH', 'NAMAYINGO WEST', 'NAMAYUNJU'],
        'NAMBUGU WARD': ['BUWAYE', 'BUYINJA', 'NAMBUGU', 'WALUMBE'],
        'NASINU WARD': ['BUNYIKA A', 'BUNYIKA B', 'NASINU CENTRAL', 'NASINU NORTH', 'NASINU SOUTH'],
      },
      'SIGULU ISLANDS': {
        'BUMALENGE': ['BULAGAYE LOWER', 'BULAGAYE UPPER', 'BUTANIRA', 'LYANJALA', 'NAMUDIA', 'SECHO'],
        'NAMPONGWE': ['BUGOMA', 'BUSERO', 'HASUSUNI', 'MAYAKALO', 'NAMUGONGO', 'RADANGA'],
        'RABACHI': ['BUGEGE', 'BULARI', 'BUMAYINDI', 'BUYANGA', 'LUBIRU', 'RABACHI T/C'],
        'SIGULU MANGA': ['BUBUBI', 'BUHABOCHA', 'BUHWANA', 'BUTAMALA', 'BUYIMA', 'MATOLO'],
        'SIGULU MUKANI': ['BANGO', 'BUHOBA \'A\'', 'BUHOBA \'B\'', 'MUKANI', 'SIEMBA \'A\'', 'SIEMBA \'B\''],
      },
    },
    'NAMUTUMBA': {
      'BUGOBI': {
        'BUWANGA': ['BUWANGA A', 'BUWANGA B', 'LUGULU', 'MAGHANGA'],
        'KIBIGO': ['MAKOMA A', 'MAKOMA B', 'MAKOMA C'],
        'KISIIRO': ['ISAMBA', 'KAMWOKYA', 'KISIIRO A', 'KISIIRO B', 'KISIIRO CENTRAL', 'KISIIRO EAST', 'KISIIRO NORTH', 'KISIIRO WEST'],
        'MAKENHA': ['BUNANGWE', 'KIWOLOMERO A', 'KIWOLOMERO B', 'MAKENYA A', 'MAKENYA B', 'WAKOOLI'],
        'NAKAZINGA': ['IVULE', 'KITUMBA', 'MBULA ITAKALI', 'NAKAZINGA A', 'NAKAZINGA B', 'NKOKO'],
      },
      'BUGOBI TOWN COUNCIL': {
        'BUGOBI B WARD': ['BUGOBI B', 'BUGOBI WEST', 'KINYOLE', 'KOOTOLI', 'WAKA WAKA'],
        'BUGOBI CENTRAL WARD': ['BUGOBI A', 'BUGOBI CENTRAL', 'KASOMA', 'NKULEGA'],
        'BUGOBI EAST WARD': ['BUGOBI EAST', 'MATABA', 'NABUKONGOYA', 'WAMUGERA'],
        'BUKENGA WARD': ['BUKENGA A', 'BUKENGA B', 'BUKENGA CENTRAL', 'NSONGWE A', 'NSONGWE B'],
        'KIBIGO WARD': ['ASUPASA', 'ITENGESA', 'KIBIGO A', 'KIBIGO B'],
        'TOWN SIDE WARD': ['MUGEMULE', 'NABUNERE', 'NASIRALO A', 'NASIRALO B', 'TOWN SIDE'],
      },
      'BULANGE': {
        'BUBUTYA': ['BUBUTYA', 'BUNGHONO', 'BUSIIRO', 'BUTYABULE', 'IGULAMUBIRI', 'NAMASEBE'],
        'BUKENGA': ['BUBUSA', 'BUFUYA', 'BUSINDA A', 'BUSINDA B', 'IGHALANGIRE', 'NABUTYERERE'],
        'BULANGE': ['BUKULUBA', 'BULANGE', 'BWAYUYA', 'NABIRALA', 'NALUKERO', 'NGANZO'],
        'BUWAGA': ['BUTOGOLI A', 'BUTOGOLI B', 'BUWAGA B', 'BUWAGA CENTRAL', 'MAGOOLA A', 'MAGOOLA B', 'NAWAMBOGO A', 'NAWAMBOGO B'],
        'KIREREMA': ['BUKALEBA', 'BUNAIBAMBA A', 'BUNAIBAMBA B', 'BUYANGU', 'KIREREMA I', 'KIREREMA II', 'KIREREMA III/KAYOBYO', 'NABANJA', 'NAKIBENGWE'],
        'KISENYI': ['BUBWIKA', 'KISENYI', 'LUBIRA', 'LUBUMBA', 'NAMUSINJIRI', 'NAWANDAGALA A', 'NAWANDAGALA B', 'NAWANDYO A', 'NAWANDYO B'],
        'MPUMIRO': ['BUBWOLI', 'BUDOMERO', 'BUDUNDA', 'BUGAALI', 'BULYANSALA', 'BUNAIBANI', 'BUYOBOYA', 'KIBAALE A', 'KIBAALE B', 'MPUMIRO'],
        'NAWANKOFU': ['BUSEGERA A', 'BUSEGERA B', 'NALENDE A', 'NALENDE B', 'NAMALOWE', 'NAWANKOFU A', 'NAWANKOFU B'],
      },
      'IVUKULA': {
        'BUDOMERO': ['BUDOMERO', 'BUGWE', 'BUTAMOGA', 'KAVULE', 'KIRWANIRE', 'NAMUSITA A', 'NAMUSITA B'],
        'IVUKULA': ['BUKAYE', 'BULEMBO', 'BULEMBO EAST', 'BWIITE', 'IVUKULA'],
        'KAMUDOKE': ['IDUDI', 'KIRANGA', 'NALUWERERE'],
        'KIMENYULO': ['BUNAMAIZI', 'IGONGERYA', 'KIMENYULO', 'NABITOVU', 'NAWAIBETE'],
        'KIRONGO': ['BUPALUKA', 'KIRONGO', 'MAWEMBE', 'NAISAMULA', 'NAWAMBIRI'],
        'KISEWUZI': ['BUDUMBA', 'BUKALAMAISO', 'KISEWUZI', 'MAKUUTU', 'NAMWENDA CENTRAL', 'NAMWENDA I', 'NAMWENDA II', 'NAMWENDA III'],
        'NABITULA': ['BULYOWA A', 'BULYOWA B', 'BUMEIGERA', 'NABITULA', 'NABITULA CENTRAL', 'NABWEYO', 'NAMULIKIRYA', 'PALLISA'],
      },
      'IVUKULA TOWN COUNCIL': {
        'BUGABULA WARD': ['BUGABULA A', 'BUGABULA B', 'BWIITE', 'BWIITE B'],
        'GASANI WARD': ['BUDYANGA', 'GASANI A', 'GASANI B'],
        'IVUKULA WARD': ['IVUKULA C', 'IVUKULA CENTRAL', 'IVUKULA TOWN A', 'IVUKULA TOWN B'],
        'KAKOOLA WARD': ['KAKOOLA A', 'KAKOOLA B', 'KAKOOLA C', 'KAKOOLA CENTRAL', 'KAMEDE ZONE'],
        'MPANDE WARD': ['BUGOMBA ZONE', 'KAKUMANYO', 'MPANDE A', 'MPANDE B', 'MPANDE CENTRAL'],
        'NAKAZINGA WARD': ['BUGWERE', 'BUSUBO', 'NAKAZINGA A', 'NAKAZINGA B'],
        'NAWANKIMA WARD': ['KAMUDOOKE', 'NALUWERERE A', 'NALUWERERE B', 'NAWANKIMA A', 'NAWANKIMA B'],
      },
      'KAGULU': {
        'BUGIRI': ['BUGIRI', 'KASEDE', 'NABISWA', 'NAKAWA'],
        'IRWANIRO': ['IRWANIRO', 'NABIGALATA', 'NAWAMBIRI', 'TUBANDANGANE', 'WAKABWA'],
        'KAGULU': ['BUGANZA', 'BUKUFA', 'BUTEGO', 'KAGULU', 'KISYAIKE', 'NAMUSAYI'],
        'NABWEYO': ['IZIMBA', 'KAWANAMO', 'LUZINGA', 'NABWEYO', 'NAWANTALE'],
      },
      'KIBAALE': {
        'KASOZI': ['BUSOGA', 'BWIGOMBE', 'KASOZI', 'KASOZI CENTRAL', 'KASOZI MAYUGE', 'NKANJA'],
        'KIBAALE': ['BULYAMPITI', 'BUVUNDYA A', 'BUVUNDYA B', 'KIBAALE A', 'KIBAALE B', 'NKERWE'],
        'KIRANGA': ['BUKYIKA', 'BULERE', 'KAKOGE', 'KAKUNYU', 'KIMUMWE', 'KIRANGA A', 'KIRANGA B', 'NAKITENGETA', 'NAWANGOMBE'],
        'KISEGA': ['KAWESYE', 'KAWESYE B', 'KAWESYE CENTRAL', 'KISEGA A', 'KISEGA B', 'NAKYERE B', 'NAKYERE I'],
        'NAMAKOKO': ['BUWALI', 'BUWALI CENTRAL', 'NAMAKOKO A', 'NAMAKOKO B', 'NAMAKOKO CENTRAL', 'NAMUNTENDA A', 'NAMUNTENDA B'],
        'NAWANGISA': ['BUDEBERO', 'BUDWAPA A', 'BUDWAPA B', 'BUKOSE', 'BUNYINKIRA', 'BUWAYA', 'KAVULE', 'NAIGOMBWA', 'NAWANGISA IA', 'NAWANGISA IB', 'NAWANGISA II'],
      },
      'KIBALE TOWN COUNCIL': {
        'BUGUMBA WARD': ['BUGANDA', 'BUGUMBA', 'BWANGU A', 'BWANGU B', 'NAWANDYO B'],
        'MPULIRA WARD': ['BUKWALI', 'KAMWOKYA', 'MPULIRA', 'MPULIRA B', 'NAWAIKOKE A', 'NAWAIKOKE B', 'NAWANDYO A'],
        'NABISOIGI CENTRAL WARD': ['BUKUBEMBE', 'BUYEMBA', 'BUYINDA', 'KISEJJERE', 'NABISOIGI II', 'NABISOIGI III', 'NSIBIRO'],
        'NABISOIGI WARD': ['BUSERA', 'BUYINDA CENTRAL', 'BUYINDA II', 'NABISOIGI I'],
        'NAKYEERE WARD': ['BUDABA', 'NABUKALU', 'NAKYERE CENTRAL', 'NAKYERE II', 'NKWANZI', 'NKWANZI B', 'WALUMBE'],
      },
      'KIWANYI': {
        'IRONDO': ['BUGALIMU', 'BUGANZA', 'BUKOSE', 'BULALAKA', 'BUTABILA', 'BWIGEMBE', 'IRONDO', 'NABYAMA'],
        'IZIRANGOBI': ['BUSAMO', 'BUSILE', 'BUYUGU', 'IZIRANGOBI A', 'IZIRANGOBI B', 'KAITI', 'MPOLYA BIGELE'],
        'KIWANYI': ['BUBINGA', 'KAKOOLA', 'KASODO', 'KASONGWE', 'KATENGELERE', 'KIWANYI', 'NABIKABALA', 'NAIMULI'],
        'MULAMA': ['BUTOBOLE A', 'BUTOBOLE B', 'BUWINDI', 'MULAMA', 'NABISAKA', 'NAKABALE'],
        'NABINYONYI': ['BUYUNGA', 'GADUMIRE A', 'GADUMIRE B', 'KIGWERO A', 'KIGWERO B', 'NABINYONYI I', 'NABINYONYI II', 'NABINYONYI III', 'NANDEREMA', 'NAWANSALYA'],
        'NAMALEMBA': ['BUKENYE', 'BULOLO', 'BULYANSWA', 'BUTEGO', 'KYALA B', 'KYARA A', 'NAMALEMBA'],
        'NAMBULA': ['BUGABWE', 'BULEMA', 'BUSAMBAIZA', 'KALITUMBA', 'NABIYUNGI', 'NAMBULA', 'NAWAMPOKOYO', 'NAWANSEKESE'],
      },
      'KIZUBA': {
        'IGERERA': ['BUBBALYA', 'IGERERA', 'MAWUNGWE A', 'MAWUNGWE B', 'NAMUKOGE'],
        'KIZUBA': ['BUNYANZI', 'BUWOOLA', 'KISIMO A', 'KISIMO B', 'KITAAMA', 'KIZUBA'],
        'NAKALOKWE': ['BUNYAGWE A', 'BUNYAGWE B', 'NAKALOKWE', 'SEMBERA'],
        'NAWANSAGWA': ['KAVULE', 'NAKAGHANO', 'NAMULU', 'NAMUSENO', 'NAWANSAGWA', 'NTALINGA'],
      },
      'MAGADA': {
        'BUYANGE': ['BUKASA', 'BUYANGE', 'KAMWENGE', 'KATAKWITE', 'NFUKIRANI'],
        'KATEGERE': ['BUKEMBA A', 'BUKEMBA B', 'BUKENYE', 'JALUKO', 'KATEGERE A', 'KATEGERE B', 'NAKABALE A', 'NAKABALE B', 'NAMWENGE'],
        'MAGADA NORTH': ['BUKALEMA', 'BULAGAZI A', 'BULAGAZI B', 'BUNYANA', 'MAGADA A', 'MAGADA B', 'NABUKALU A', 'NABUKALU B', 'NAKABAALE', 'NAMAVUNDU'],
        'MAGADA SOUTH': ['BUGALO', 'BUKISITA', 'BUKULEMA', 'KASAALE A', 'KASAALE B', 'NABISOLI', 'NALUSWA'],
      },
      'MAZUBA': {
        'ISITA': ['BUDHEERO', 'ISITA A', 'ISITA B', 'IZIMBA', 'MUKOOGE A', 'MUKOOGE B', 'NAKABALE A', 'NAKABALE B'],
        'KAGAIRE': ['KAGAIRE', 'KAGOLA', 'KASOLO', 'MULEMBA', 'MULEMBA TRADING CENTRE'],
        'MAZUBA': ['BUKENE', 'BUTAMBA I', 'BUTAMBA II', 'KIMOMBASA', 'MAZUBA A', 'MAZUBA B', 'MAZUBA CENTRAL', 'MPOLOGOMA', 'MPOLOGOMA CENTRAL'],
        'MPEIZYA': ['IRIMBI A', 'IRIMBI B', 'MPENZYA A', 'MPENZYA B', 'NADWALI CENTRAL'],
        'NAWANZALI': ['BUDAWUNA', 'BUDAWUNA CENTRAL', 'KAMUGOYA', 'NAKULUBU', 'NAKULUBU TRADING CENTRE', 'NAWANZALI'],
        'NSOOLA': ['BUKYEDE', 'BUMBAALA', 'KAKUNYU', 'KASULETA A', 'KASULETA B', 'NAMUWAYO', 'NSOOLA A', 'NSOOLA B'],
      },
      'NABWEYO': {
        'BUDATU': ['BUDATU', 'BUGAIZA', 'BUGANZA', 'BULIMBA A', 'BULIMBA B', 'BUNYANA', 'ITENGESA', 'LWAMBA', 'NABISWA', 'NAMUSILISILI'],
        'BUSINI': ['BUNYEKERO', 'BUSINI A', 'BUSINI B', 'BUSINI CENTRAL', 'BWISAMU', 'KYAMWA A', 'KYAMWA B', 'MBOGO'],
        'NABWEYO': ['BUSUBI', 'BUZIMBA', 'KALINAKI', 'NABUGUZI', 'NABWEYO A', 'NABWEYO B', 'NABWEYO CENTRAL', 'NALUEWERERE T.CENTRE', 'NANVUNANWA'],
      },
      'NAMUTUMBA': {
        'ITUBA': ['ITUBA A', 'ITUBA B', 'ITUBA C', 'NAMUWONDO A', 'NAMUWONDO B'],
        'KIGALAMA': ['BULAFA', 'KIGALAMA', 'NAMAKOBA A', 'NAMAKOBA B', 'SABAGABO'],
        'NAKYEERE': ['BULYABWITA A', 'BULYABWITA B', 'KASEDHERE A', 'KASEDHERE B', 'KASIMIZI', 'NAKYERE'],
        'NAMATO': ['NAMATO CENTRAL', 'NAMATO EAST', 'NAMATO WEST', 'NAWAMPITI'],
        'NAWAMPANDU': ['NAWAMPANDU A', 'NAWAMPANDU B', 'NAWAMPANDU C'],
      },
      'NAMUTUMBA TOWN COUNCIL': {
        'NAMUTUMBA CENTRAL WARD': ['BUDONGO', 'KANGULUMO A', 'KANGULUMO B', 'NAMUTUMBA A', 'NAMUTUMBA B'],
        'NAMUTUMBA NORTH WARD': ['BUKAABA', 'BULOGO', 'KALAMIRA', 'MATYAMA'],
        'NAMUTUMBA SOUTH WARD': ['BUWAMBI', 'ITONKO'],
      },
      'NANGONDE': {
        'BUWALIRA': ['BUDIDO', 'BUGUMULA', 'BUNANGWE', 'BUNANGWE ESTATE', 'BUWALIRA', 'BUWONGERA', 'KAKOKOLA'],
        'IWUNGIRO': ['IWUNGIRO', 'KIKALU', 'MAKWI'],
        'KISEGA': ['BUGAYI', 'BUHOLO', 'IZINGA', 'KISEGA'],
        'LWATAMA': ['KABIRA', 'LWATAMA A', 'LWATAMA B', 'NAISAHE', 'NAWANSIMBI'],
        'NAMAKOKO': ['BUMANI', 'MANGAFE', 'NAMAKOKO A', 'NAMAKOKO B', 'ZAAGIRA'],
      },
      'NANGONDE TOWN COUNCIL': {
        'BUNANGWE WARD': ['CENTRAL ZONE', 'ESTATE', 'ESTATE B', 'ESTATE ZONE A'],
        'BUTIMBO WARD': ['BUTIMBO ZONE A', 'BUTIMBO ZONE B', 'KAKUKU', 'KUJJUNA ZONE'],
        'IKWIZI WARD': ['IKWIZI CENTRAL ZONE', 'IKWIZI ZONE A', 'IKWIZI ZONE B'],
        'IWUNGIRO WARD': ['IWUNGIRO CENTRAL ZONE A', 'IWUNGIRO ZONE B', 'WAMUNYA ZONE'],
        'KIGUNDA WARD': ['BUISALANYA', 'KIGUNDA ZONE B', 'NAISANGA ZONE', 'NAMULAMBA ZONE', 'NANKOKI ZONE'],
        'KITAIGALWA WARD': ['KALALU ZONE', 'KITAIGALWA ZONE A', 'KITAIGALWA ZONE B'],
        'NANGONDE CENTRAL WARD': ['NANGONDE CENTRAL ZONE', 'NANGONDE ZONE A', 'NANGONDE ZONE B'],
        'NANGONDE WARD': ['BUKOSE ZONE', 'KABAKUBYA ZONE', 'MBIRI ZONE', 'NKONO ZONE'],
        'NAWANDAKA WARD': ['KAKOOLA ZONE A', 'KAKOOLA ZONE B', 'KANGAIHWA ZONE', 'NAWANDAKA ZONE'],
      },
      'NAWAIKONA': {
        'BUKONTE': ['BUDHATEMWA A', 'BUDHATEMWA B', 'BUDIGO', 'BULAGALA', 'BUYANGA', 'KISENHO', 'NAWAIBETE', 'NKONTE'],
        'KIVULE': ['BUBINGA', 'KIVULE', 'NABITULUNTU', 'NAWAMPIITI'],
        'NAKAWUNZO': ['BUKAIRU', 'BULONGO', 'BUMOGA', 'KISIKI', 'MATAAGA', 'NAKAWUNZO I', 'NAKAWUNZO II', 'NALUSOLO'],
        'NAWAIKONA': ['BUKEBWE', 'BUKUDUMIRA', 'BUTAGALA', 'NABIKENGE', 'NAWAIKONA \'\'B\'', 'NAWAIKONA \'A\'', 'WALUMBO'],
      },
      'NSINZE': {
        'BUBAGO': ['BUBAGO', 'BUDHEBERO A', 'BUDHEBERO B', 'KASULEETA', 'MEERU', 'NABIGHERYA', 'NAMBOOTE', 'NAMUKENKEDU', 'NKOLOOTA'],
        'BUNYAGWE': ['BUNYAGWE', 'CENTRAL BUNYAGWE', 'KAPASULI', 'MALIGA', 'MALIGA TRADING CENTRE'],
        'BUWONGO': ['KATENGEREIRE', 'NAIGOMBWA', 'SIIRA'],
        'ISEGERO': ['BUSEENE', 'BUWOITO', 'ISEGERO A', 'ISEGERO B', 'ISEGERO MAILO', 'NAMUKOOGE', 'NDIKWITAMAIRA'],
      },
      'NSINZE TOWN COUNCIL': {
        'BUKENHE WARD': ['BUKENHE', 'GATONGANA', 'KIBUKA', 'WALUMBE'],
        'BUKOLO WARD': ['BUGEMBE', 'BUKOLO', 'BUSUBO', 'WALUTENTE'],
        'BUWONGO A WARD': ['BUWONGO A', 'CHURCH ZONE', 'NABUSIGO'],
        'BUWONGO B WARD': ['BUWONGO B', 'IBALE', 'NABAGISA'],
        'BUYUNGA WARD': ['BUYUNGA', 'SALIM'],
        'NABUKALU WARD': ['KIZUNGU', 'NABUKALU A', 'NABUKALU B'],
        'NAMASERE WARD': ['BABUZE', 'KIBOGA', 'NAMASERE'],
        'NAMAVUNDU WARD': ['KYABAZINGA', 'NAMAVUNDU', 'NAMAVUNDU CENTRAL', 'NKOTA'],
        'NSINZE WARD': ['MUSEREBENDE', 'NSINZE', 'NSINZE CENTRAL', 'YOSIYA'],
      },
    },
  };

  /// Get all districts
  static List<String> getDistricts() {
    return _locationData.keys.toList()..sort();
  }

  /// Get subcounties for a specific district
  static List<String> getSubcounties(String district) {
    if (!_locationData.containsKey(district)) return [];
    return _locationData[district]!.keys.toList()..sort();
  }

  /// Get parishes for a specific district and subcounty
  static List<String> getParishes(String district, String subcounty) {
    if (!_locationData.containsKey(district)) return [];
    if (!_locationData[district]!.containsKey(subcounty)) return [];
    return _locationData[district]![subcounty]!.keys.toList()..sort();
  }

  /// Get villages for a specific district, subcounty, and parish
  static List<String> getVillages(String district, String subcounty, String parish) {
    if (!_locationData.containsKey(district)) return [];
    if (!_locationData[district]!.containsKey(subcounty)) return [];
    if (!_locationData[district]![subcounty]!.containsKey(parish)) return [];
    return _locationData[district]![subcounty]![parish]!..sort();
  }

  /// Validate if a location hierarchy is valid
  static bool isValidLocation({
    required String district,
    String? subcounty,
    String? parish,
    String? village,
  }) {
    if (!_locationData.containsKey(district)) return false;
    
    if (subcounty != null) {
      if (!_locationData[district]!.containsKey(subcounty)) return false;
      
      if (parish != null) {
        if (!_locationData[district]![subcounty]!.containsKey(parish)) return false;
        
        if (village != null) {
          if (!_locationData[district]![subcounty]![parish]!.contains(village)) {
            return false;
          }
        }
      }
    }
    
    return true;
  }

  /// Add new location data (for future expansion)
  static void addLocationData({
    required String district,
    required String subcounty,
    required String parish,
    required String village,
  }) {
    // Initialize district if not exists
    if (!_locationData.containsKey(district)) {
      _locationData[district] = {};
    }
    
    // Initialize subcounty if not exists
    if (!_locationData[district]!.containsKey(subcounty)) {
      _locationData[district]![subcounty] = {};
    }
    
    // Initialize parish if not exists
    if (!_locationData[district]![subcounty]!.containsKey(parish)) {
      _locationData[district]![subcounty]![parish] = [];
    }
    
    // Add village if not exists
    if (!_locationData[district]![subcounty]![parish]!.contains(village)) {
      _locationData[district]![subcounty]![parish]!.add(village);
    }
  }

  /// Get statistics about the location data
  static Map<String, int> getStatistics() {
    int totalDistricts = _locationData.length;
    int totalSubcounties = 0;
    int totalParishes = 0;
    int totalVillages = 0;
    
    _locationData.forEach((district, subcounties) {
      totalSubcounties += subcounties.length;
      subcounties.forEach((subcounty, parishes) {
        totalParishes += parishes.length;
        parishes.forEach((parish, villages) {
          totalVillages += villages.length;
        });
      });
    });
    
    return {
      'districts': totalDistricts,
      'subcounties': totalSubcounties,
      'parishes': totalParishes,
      'villages': totalVillages,
    };
  }

  /// Get all locations for a specific district (for debugging/admin purposes)
  static Map<String, dynamic> getDistrictData(String district) {
    if (!_locationData.containsKey(district)) return {};
    
    Map<String, dynamic> districtInfo = {
      'district': district,
      'subcounties': [],
    };
    
    _locationData[district]!.forEach((subcounty, parishes) {
      Map<String, dynamic> subcountyInfo = {
        'name': subcounty,
        'parishes': [],
      };
      
      parishes.forEach((parish, villages) {
        subcountyInfo['parishes'].add({
          'name': parish,
          'villages': villages,
        });
      });
      
      districtInfo['subcounties'].add(subcountyInfo);
    });
    
    return districtInfo;
  }
}
